### ISSUE TITLE
Center-point and grid overlay option

### ISSUE THREAD

**Issue by TomPickett671** [deepskystacker/DSS#101]
I have found something that is missing on DSS that is needed.
When selecting a reference frame that has perfect stars to stack all of your subs over you also need to have the reference frame centered on your target especially when you are dithering. 
The only way to do this while inspecting and clicking on each sub frame we need to have a center-point and grid overlay option to put over the top of the display so when clicking on each image you can see where the center of your object is in the ref frame. This way you have a common center-point of ref where all of the dithered images are being stacked. 
I do not know if this option is already available but if it is please let me know where it is.

**Comment by perdrix52** [comment]
This question and discussion should be on the mailing list not here.

Please join the mailing list at [](https://groups.io/g/DeepSkyStacker/) and post you question/suggestion there

PS Also explain why you believe you need this.
