### ISSUE TITLE
User reports Bayer Drizzle: "Adjust Bayer - Compute Adjustment" is single threaded

### ISSUE THREAD

**Issue by perdrix52** [deepskystacker/DSS#102]
When some time comes available perhaps one of us can look at this?

See: https://groups.io/g/DeepSkyStacker/message/24241

**Comment by mtoeltsch** [comment]
I ran tests on my Windows11 laptop (core i5-1135-g7), stacking 10 lightframes Nikon raw NEF files. 
I compared bilinear de-bayering with Bayer-drizzle.
I used DSS 4.2.6 and the latest build of 5.1.0 beta. 

I found no performance differences between bilinear and Bayer-drizzle, neither with 4.2.6 nor 5.1.0beta.

**Comment by perdrix52** [comment]
I suspected as much - closing this
