### ISSUE TITLE
Sorry, LibRaw doesn't support your Sony ILCE-7RM4 camera

### ISSUE THREAD

**Issue by 3ricj** [deepskystacker/DSS#103]
It looks like the 201910 snapshot has support for it.  

https://www.libraw.org/supported-cameras-snapshot-201910

It's not clear to me how to update the library, it seems it's baked into the executable.

**Comment by perdrix52** [comment]
It is - I will soon be releasing a new beta with Libraw 20.? builtin - the snapshot was pre-beta code.

David
