### ISSUE TITLE
Disable "LibRaw" Warning when working with Sony A7S RAW images

### ISSUE THREAD

**Issue by NGC6888** [deepskystacker/DSS#104]
Is it posible, to disable the Libraw warning that Sony RAWs are not supported?
As I use a Sony A7S and DSS works very well with the *.ARW Files.
I only have to press OK and then DSS starts stacking.

![image](https://user-images.githubusercontent.com/38884636/86768431-d8c49c80-c04d-11ea-831b-383fcabe98df.png)

With best regards
N. Reuschl

**Comment by perdrix52** [comment]
No,  The warning is there for a reason. I don't understand why the camera name is in Japanese ?   Is this a grey import

The next release of LibRaw (real soon now) will release the A7S and will be built into the next beta of DSS
