### ISSUE TITLE
JPEG mistaken for RAW in 4.2.3

### ISSUE THREAD

**Issue by SteampunkIslande** [deepskystacker/DSS#106]
Hello all,
I think I might post my problem here, since it looks more like a bug than a feature.
I have three jpeg files shot at several speeds, and when opening them as light images one of them appears as RAW image.
(Even though its file extension is JPEG). Others two also show with weird characters for the date/time field but it doesn't seem to be an issue.

I am shooting directly in xfine jpeg, with Sony ILCE 6400. Attached are the three images (458 is the one messing up on my computer).
![DSC00456](https://user-images.githubusercontent.com/64743278/87794307-b51c0600-c846-11ea-9515-6e4c36857a14.JPG)
![DSC00457](https://user-images.githubusercontent.com/64743278/87794410-de3c9680-c846-11ea-9f0e-5d2659cbd8f9.JPG)
![DSC00458](https://user-images.githubusercontent.com/64743278/87794522-0a581780-c847-11ea-9a08-719b845d67a5.JPG)

**Comment by perdrix52** [comment]
Filenames totally mangled by uploading to github.

However I've DLed them all and will take a look.

**Comment by perdrix52** [comment]
Times were also wrong in Beta 5

**Comment by perdrix52** [comment]
I've fixed the problem by not allowing the code to attempt opening any jpg files as raw, and corrected the date/time display (SYSTEMTIME struct not fully intialised to zero).

It will ship in 4.2.4 beta 5

**Comment by perdrix52** [comment]
PS STRONGLY SUGGEST you use RAW instead of jpg

**Comment by SteampunkIslande** [comment]
> 
> 
> PS STRONGLY SUGGEST you use raw instead of jpg, which you will be able to do in 4.2.4 Beta 5 as it uses LibRaw 0.20.
> 
> For earlier versions shoot in raw and convert to dng

Yes, this was more like exploring features, I only use RAW now and it works perfectly !
Thank you for taking the time to fix it anyway, great software !

**Comment by perdrix52** [comment]
Fixed in 4.2.4
