### ISSUE TITLE
Feature request - Need crop for very large Final output(3x drizzle)

### ISSUE THREAD

**Issue by xingxinghuo1000** [deepskystacker/DSS#107]
Need crop for very large Final output(3x drizzle or 2x drizzle)

When I stack multiple 360 mega pixel DLSR DNGs, the Final output in 3x-drizzle mode is very large
1.4GB 32bit float point TIFF format
or  1.3 GB 16bit int TIFF format

Both of them is not able to be opened in Photoshop or  Pixinsight LE

So when export Final output, a  simple crop is Need.   Because I Need only a small part of the final image

**Comment by perdrix52** [comment]
Defining a custom rectangle before you start that includes the area of interest will achieve what you want.   That is precisely that that is for.

360 MegaPixel images - no DSLR produces an image that big (that I am am aware of).  I know some of the large format cameras create images about 100Mp,

Why are you you using Drizzle for such high resolution images anyway - Drizzle is for improving the resolution of under-sampled images and your images are highly unlikely to be undersampled.

**Comment by xingxinghuo1000** [comment]
Sorry, a mistake.  I used Pentax K-1, 36 MegaPixel  DSLR.

**Comment by xingxinghuo1000** [comment]
![图片](https://user-images.githubusercontent.com/7380096/89170073-b7ee5900-d5b1-11ea-88f7-76c95418ac48.png)

**Comment by perdrix52** [comment]
Obviously you need to draw the rectangle on the image :

![image](https://user-images.githubusercontent.com/20211762/89173144-b609a300-d57b-11ea-9dca-369cee3d0c9b.png)

**Comment by perdrix52** [comment]
Try using the help!
