### ISSUE TITLE
Problem to open dark files

### ISSUE THREAD

**Issue by arnaudastro** [deepskystacker/DSS#111]
I have an issue with dark files.
When i try to open a dark, i have the error message : "could not open the named file"

**Comment by perdrix52** [comment]
Please join the DeepSkyStacker mailing list at <https://groups.io/g/DeepSkyStacker/> and start a discussion there.

This issues page is largely used for the development team

It would help if you provide more details when you do post to the mailing list (e.g. what type of file, what release of DSS) etc..

Thanks
David
