### ISSUE TITLE
Themes Proposal

### ISSUE THREAD

**Issue by Zi7ar21** [deepskystacker/DSS#113]
The current GUI is not ideal for all situations. Currently, the interface is pure white. This is a bad thing if you are using a laptop out in the field and need to stack without DSS Live. I propose that 2 themes other than the default interface are added.
1. Regular Dark: A dark monochromatic theme that is easy on the eyes when stacking at night.
2. Night Dark: A dark red tinted theme that matches other astronomy programs. It in theory cuts the light emission of the display in thirds, and would be better for a laptop out in the field situation.

**Comment by perdrix52** [comment]
Please use the DeepSkyStacker group on Groups.io for suggestions and problems with stacking files.
