### ISSUE TITLE
Nikon Z 7 RAW files reported as not supported by DSS 4.2.4

### ISSUE THREAD

**Issue by rggibb** [deepskystacker/DSS#114]
LibRaw 0.20 lists Nikon Z7 as a supported camera since 2018-12-12, and I have fastrawviewer 1.6 which handles the files without any apparent problem. But after upgrading DSS 4.2.3 to DSS 4.2.4, DSS still warns "Sorry, LibRaw doesn't support your Nikon Z 7 camera" in a popup window when you select the first Z7 NEF for viewing after starting DSS. The image is then displayed with a strong red tint. I note that the camera is listed in supported cameras as "Nikon Z7" but the warning says "Nikon Z 7" as above, ie with a space between the Z & 7, dont know whether this is significant. After the first warning message, when subsequent Z7 NEF files are selected for displaying they are displayed with the same red tint but without the warning. If a proceed to process the images DSS doesnt complain but the histogram of the resulting image has a very narrow peak, and DSS's recomended setings imply I'm using a modded DSLR and possibly narrow band (eg Halpha filters) neither of which are the case. As a precaution I uninstalled the upgraded DSS 4.2.4, and reinstalled it from scratch, but that hasnt changed the behaviour. The display of the Z7 NEF files has changed between 4.2.3 and 4.2.4, in 4.2.3 the images showed as completely misinterpreting the size - ie with very strong horizontal RGB banding.

**Comment by Klaus1234567** [comment]
Same for Nikon Z 50

**Comment by perdrix52** [comment]
OK this is a problem with the way the LibRaw stores the camera names versus how the camera presents them to LibRaw.

 

Please ignore the warning.   

 

No hash tags please

**Comment by perdrix52** [comment]
Fixed in lastest release just made

**Comment by perdrix52** [comment]
Get the updated code from [https://github.com/deepskystacker/DSS/releases/latest](url)

**Comment by rggibb** [comment]
Thx, perfect - the red tint is gone in the view of the raw image, and thx also for the hints, I'm just getting back into this - last half serious imaging I did was with 4x5 glass plates and photomultiplier tubes. I'll use the mail list next time :)
