### ISSUE TITLE
TIF files loaded in Photoshop, are corrupted when saved again as TIF

### ISSUE THREAD

**Issue by Menno5** [deepskystacker/DSS#115]
DSS 4.2.4 64bit, Photoshop CS6 64bit, Windows 10 Pro 64bit

DSS saves as TIF, opening and processing in Photoshop works fine.
But then when saving that same file as TIF again, the file is corrupted. Not only that file but every file saved in Photoshop as TIF, no matter what file. Restarting Photoshop solves it.
This was not happening with DSS 4.2.3.
Attached files: the corrupted image (converted to JPG because of file size) and the image as it should be.

![Autosave003](https://user-images.githubusercontent.com/56191878/89751294-bc45d500-dacf-11ea-96e3-097eb6453466.jpg)

![Autosave003](https://user-images.githubusercontent.com/56191878/89751143-2dd15380-dacf-11ea-88ed-55bbced2e893.jpg)

**Comment by perdrix52** [comment]
Sounds like this can't a DSS bug to me

**Comment by Menno5** [comment]
It is somehow, DSS 4.2.3 was fine, this only happens now with DSS 4.2.4.

**Comment by perdrix52** [comment]
4.2.4 changed to write TIFF files in strips

**Comment by perdrix52** [comment]
So no not a DSS bug IMHO

**Comment by perdrix52** [comment]
My testing shows that the problem doesn't occur in PS CC 2020 - can load 32 bit tif from DSS OK and save as 32 bit OK, also convert to 16 bit and that saves correctly as well.

**Comment by Menno5** [comment]
Okay, thanks for looking into it. Back to DSS 4.2.3 then for me :)

**Comment by perdrix52** [comment]
Do I gather you're using an older version of PS?

**Comment by Menno5** [comment]
Yes, CS6 does all I want despite the constant nag that I should really use their subscribed stuff, cloud, an so on.

**Comment by Lalo80** [comment]
The same thing happens with photoshop CC2019 and DSS4.2.4. installing v.4.2.3 back everithing is OK

![Untitled-2](https://user-images.githubusercontent.com/69729603/90318399-83bf5480-df30-11ea-9a66-10e7f2ba3c70.jpg)

**Comment by perdrix52** [comment]
Please will you take this to the DeepSkyStacker mailing list on groups.io (you'll need to join the list).   I'm not disputing that there's a problem here, it's just that (so far I've failed in all my attempts to reproduce it).     Please state exactly what you did that works (the right hand image), and what you did to end up with the failure (the left hand image).   The more minds we get looking at this the better.

Reproducing a problem is often (not always) 80% of the battle.

David

**Comment by Menno5** [comment]
Just joined there, will mention it.

**Comment by Lalo80** [comment]
the right hand image is original 32bit unchanged file from DSS v4.24 and left hand is converted to 16bit in ps2019.
also the same thing hapens on Adobe Photoshop 2020. Version: 21.0.2 20191122.r.57 2019/11/22

**Comment by perdrix52** [comment]
Please take this to the mailing list for discussion.
