### ISSUE TITLE
Output file is Autosave.tif even if instructed otherwise

### ISSUE THREAD

**Issue by Klaus1234567** [deepskystacker/DSS#116]
![DSS Output Settings](https://user-images.githubusercontent.com/69441575/89767580-8702ac80-dafa-11ea-943e-601b8146534f.PNG)

The output file is written to the folder containing the reference frame as Autosave.tif even though it was specified to be written to the folder containing the file list as <file list>.tif

Regards,
Klaus

**Comment by perdrix52** [comment]
I just tested this in several scenarios, and have not been able to reproduce the problem - the file is written to the folder containing the file list file.

**Comment by Klaus1234567** [comment]
Uninstall and reinstall did the trick! Works as advertised now.

**Comment by perdrix52** [comment]
OK thanks for letting me know
