### ISSUE TITLE
Some .CR3 files cannot be read and cause DeepSkyStacker to freeze

### ISSUE THREAD

**Issue by szotsaki** [deepskystacker/DSS#118]
When you try to open some .CR3 files, DeepSkyStacker freezes. Interestingly, for most of them it works.

In this share I put some good and some "bad" files for you to be able to reproduce the issue: https://mega.nz/folder/xYoFiLKJ#4VWNX4brr2V0eV7gnu0K6w.

Just for reference, ACR (Camera Raw) can open all of them.

DSS version: 4.2.4.

**Comment by perdrix52** [comment]
Interesting - thanks for providing the files.

David

**Comment by perdrix52** [comment]
Those files also cause Windows Explorer to crash (after hanging for a while).

**Comment by perdrix52** [comment]
Did they come straight out of the camera or had you done things with them?

David

**Comment by perdrix52** [comment]
Apparently they're "truncated" files (invalid) and LibRaw loops when it tries to open them.  They have a fix but no released yet.

**Comment by szotsaki** [comment]
Thank you for investigating. They did come out from the camera this way but it seems that the new SD card is defective. I'll return it.

Just a reference for future readers: this commit should fix it in LibRaw according to your comment: https://github.com/LibRaw/LibRaw/commit/cfb66cb2372b373961321cb7ebeae733030fb16c.
