### ISSUE TITLE
Registering files is single threaded

### ISSUE THREAD

**Issue by szotsaki** [deepskystacker/DSS#120]
It's just a feature proposal and I don't know whether it has technical restrictions to be the way currently it is.

As I understand, registering a file is a process on its own, not depending on other files. However, on my machine this is done linearly, one file after another while theoretically all of the cores could be used for this process in "one core - one file" setup.

![image](https://user-images.githubusercontent.com/4254450/90602485-23fbce80-e1fa-11ea-9400-d4db7ff7a293.png)

DSS version: 4.2.4.

**Comment by perdrix52** [comment]
Some the the registration code is single threaded, some not.   Over time it will get more attention - if you look at the update history you'll see I've been in there before adding some OpenMP changes.
