### ISSUE TITLE
using CR3.file to stack, but can't find the final tiff file

### ISSUE THREAD

**Issue by lksimple1201** [deepskystacker/DSS#122]
Before i updating to 4.2.5, i will get the autosave.tiff file in the end. I was using DNG file to stack. after i updated, i used the CR3.file, but at the end of stacking, it shows nothing.

**Comment by lksimple1201** [comment]
update, i convert the CR3 file to DNG again, still didn't get stack result.

**Comment by perdrix52** [comment]
I'm away on holiday.  Please would post this problem on the mailing list which is here:

[](https://groups.io/g/DeepSkyStacker/)

you'll need to join the group.

Thanks, David

**Comment by jerke007** [comment]
I have the same problem. How can I solve his or where do I find the final tiff?

**Comment by perdrix52** [comment]
Same answer got to the mailing list for support

**Comment by vnaessens** [comment]
Hello,
I have the same problem if the full path of file 'Autosave.tiff' contains Unicode character.
If I remove Unicode characters, then the file is written at the end of stacking and it can be loaded.
Regards

**Comment by lksimple1201** [comment]
Thx!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by perdrix52** [comment]
Known problem - reported on the mailing list which the normal support location.

Fixed in Next (release)
