### ISSUE TITLE
Sony color RAW's (.ARW) only register as gray 16 bit depth

### ISSUE THREAD

**Issue by er1kwarm** [deepskystacker/DSS#123]
When loading color .ARW files into DSS 4.2.5 it does not register them as 16 bit color files but as 16 bit gray files.

**Comment by perdrix52** [comment]
DSS ALWAYS reports camera RAW files as 16 bit greyscale – as that is what they are before be-bayering

**Comment by er1kwarm** [comment]
Tanks for the response! Hoe can i get them to stack into a color file as output? Now my output is also grayscale

**Comment by perdrix52** [comment]
This is not the place for DSS support, the DeepSkyStacker mailing list at groups.io is the place for that.

We use this issues page for logging confirmed defects and development stuff.

BTW your output image is almost certainly NOT monochrome/grey scale.  Most likely it just needs to have the saturation increased.
