### ISSUE TITLE
Problem when saving TIFF files with Unicode or whitespace characters in file paths.

### ISSUE THREAD

**Issue by vnaessens** [deepskystacker/DSS#124]
Hello,
I am running DSS version 4.2.5 and I noticed the following issues when the program tries to write TIFF images :

- when saving 'Autosave.tif', if the path contains Unicode character (e.g. C:\Users\vnaessens\Pictures\Tenerife 2020\Nuit 1\Corral del Niño\Autosave.tif) then it cannot be written. After removing Unicode character 'ñ', it works even if there are whitespaces.

-  when saving an image from tab 'Processing > Save', it does not create any file if there is a whitespace in the path. Note that I can save to FITS in the same directory which has whitespaces in its path.
Regards

**Comment by perdrix52** [comment]
Already reported issue 117.  Fixed In Next release.
