### ISSUE TITLE
Infinite pop-ups

### ISSUE THREAD

**Issue by GajowyJ** [deepskystacker/DSS#128]
When I started monitor a folder with FITS there were some other files (no imgaes: setting, NTP logs, etc.). Program started displaying messages about "improper format" of these files in infinite loop. One can't stop poping-up new alerts.

**Comment by perdrix52** [comment]
Patient:  It hurts if I do that.  
Doctor: Don't do that then!

DSS Live doesn't like other files in the folder it is monitoring.  Known problem.
