### ISSUE TITLE
Plans for hardware (GPU) acceleration?

### ISSUE THREAD

**Issue by achalpandeyy** [deepskystacker/DSS#129]

**Comment by Jeneelk** [comment]
Hello, 
I am a bit experienced in CUDA and planning to write a parallel code which can take advantage of the GPUs. To begin with the stacking algorithms would be easy to implement CUDA kernels, but I am not very sure how it will integrate with the current implementation. Can someone point me to specific files that are related to just stacking which I can possible modify?
Thanks

**Comment by perdrix52** [comment]
StackingEngine.cpp is a good place to start :)

**Comment by mtoeltsch** [comment]
Hi, 
the issue I see is that Cuda is limited (afaik) to NVIDIA cards. That would be an unacceptable limitation for all the work that's required to get that working. 
You should consider doing it with OpenCL. That supports all relevant graphic cards.

**Comment by perdrix52** [comment]
There's also the issue of the amount of data that would need to be moved to/from the card (though you might still come out on top).

**Comment by mtoeltsch** [comment]
Agreed. 
So what you should do - I think - is to start with a decent performance profiling, IMPORTANT: with AVX vectorisation turned ON. See if you can identify a dominant performance bottleneck. 
On my computer (Intel i5-1135-g7) however, 75-80% of the time is for loading the files from disc.

**Comment by perdrix52** [comment]
Closed - unlikely to happen ATM
