### ISSUE TITLE
Nothing but a grey screen after processing. 

### ISSUE THREAD

**Issue by defless** [deepskystacker/DSS#130]
After a long time I've decided to make some photos with a **Nikon z6**. But every stacking that I've done ended up with nothing but the grey screen you can see below :

![image](https://user-images.githubusercontent.com/43884154/103684039-42851b00-4f8b-11eb-8374-0a0dde1d63e6.png)

I'm working on professionnal windows 10 and with the latest version of DSS (4.2.5). Both of TIFF and NEF formats didn't work. 
It used to work for me with my D800 but as I said it was a long time ago. 

Thanks for your help 🙏

**Comment by perdrix52** [comment]
I bet you have file or path name containing an accented character - the folder name and it will probably work.

**Comment by defless** [comment]
Thanks a lot  ! 

I thought it had been fixed with the 4.2.5 release as it is write in the changelog : 

_Correct a problem where DSS failed to read files whose path contained accented characters._

**Comment by perdrix52** [comment]
Partly fixed I fear ... I missed one
