### ISSUE TITLE
Mosaic luminance normalization

### ISSUE THREAD

**Issue by RReverser** [deepskystacker/DSS#135]
I like mosaic mode to combine images from a wider field than my lens allows, but one thing that always bothers me is the different brightness of parts that were present only in a subset of images. Here's a quick example screenshot:

![image](https://user-images.githubusercontent.com/557590/125861258-96c4c818-1172-47c3-aa4e-778e3526db86.png)

While I understand why it happens, it's not something that is easy (or,dare I say, possible) to fix in the postprocessing, so the only options when dealing with such set are:
1. Manually go through images and keep only those that overlap better with each other, losing valuable data for central parts.
2. Crop the image only to its best overlap, essentially ending up with the same thing as "intersection" mode, rendering "mosaic" mode pretty much useless.

I was wondering if DSS could instead adjust brightness of parts that were created from fewer overlapping images to match the brightness of the full overlap. This way, worst case scenario parts outside the center will be a bit more noisy / have less details, but at least the resulting look will be more consistent and easier to postprocess.

**Comment by perdrix52** [comment]
Can we move this discussion to the DeepSkyStacker mailing list on groups.io please.  Right now I can't see a good way to achieve this.  Please put a link to this issue in your post to the mailing list so folks can see the image (rather than including it in your post).

**Comment by RReverser** [comment]
Hmm, I mean, this is either a feature request or a bug report, which in either case seems to make it more appropriate for a tracking issue than mailing list IMO (I prefer the latter for general questions in other projects)...

> Right now I can't see a good way to achieve this.

Assuming equal params for each image in the stack, think this could be as simple as multiplying each resuling pixel's value by `N[current]/N[total]` where `N[current]` is the number of images that contributed to the current pixel and `N[total]` is the number of all images that form the biggest overlap.

If params for different images differ significantly, then this could be a problem, of course, and would require perhaps using the calculated "Sky brightness" value to determine a good coefficient.

In either scenario, it doesn't seem too complicated. [famous last words... 😅]

**Comment by RReverser** [comment]
Was this implemented or closed as "wontfix"?

**Comment by perdrix52** [comment]
It's not a bug for sure, it is a feature request that I asked you to raise on the discussion forum.

I will also admit it's not a simple thing to solve.
