### ISSUE TITLE
DeepSkyStacker crashes in Wine, maybe due to missing TaskbarButton implementation in Wine and missing null pointer check in DSS.

### ISSUE THREAD

**Issue by bernhardu** [deepskystacker/DSS#136]
Hello, I tried to do a little investigation about a [Wine bug about DeepSkyStacker](https://bugs.winehq.org/show_bug.cgi?id=51755).
This might be related to the source lines below. I assume that in DSS recognises in Wine a Windows 7,
but `m_taskbarList` seems to get set to NULL as there seems to be not yet an implemtation of `TaskbarButton` in Wine,
which later gets called in OnProgressInit/OnProgressUpdate/OnProgressStop and therefore leads to a crash.
If this is right, this crash could be avoided by just checking `m_taskbarList` to be a valid pointer.

https://github.com/deepskystacker/DSS/blob/11eb036e38aa0039c007fac390dbbd9e362b2bc7/DeepSkyStacker/DeepStackerDlg.cpp#L132

https://github.com/deepskystacker/DSS/blob/11eb036e38aa0039c007fac390dbbd9e362b2bc7/DeepSkyStacker/DeepStackerDlg.cpp#L170

https://github.com/deepskystacker/DSS/blob/11eb036e38aa0039c007fac390dbbd9e362b2bc7/DeepSkyStacker/DeepStackerDlg.cpp#L346-L355

https://github.com/deepskystacker/DSS/blob/11eb036e38aa0039c007fac390dbbd9e362b2bc7/DeepSkyStacker/DeepStackerDlg.cpp#L362-L366

**Comment by Crazor** [comment]
Just wanting to let people that come across this bug know that as stated in the WineHQ link, changing the Wrapper from Windows 7 to Windows XP works just fine.

**Comment by perdrix52** [comment]
WIne isn't supported
