### ISSUE TITLE
Better use of TIFF files, Astro-TIFF

### ISSUE THREAD

**Issue by han-k59** [deepskystacker/DSS#138]
There is currently an initiative to make better use of the TIFF format for astronomy. The idea is to save a FITS header in a standard way into a TIFF file. This make conversion between TIFF and FITS possible without loosing header information.

The FITS header is stored in the description tag of the TIFF file. The specification is here:
http://www.hnsky.org/astro-tiff.htm

Benefits:

    The TIFF compression algorithm makes the files smaller
    The files are readable by almost any image viewer.

The proposal is to make Deep Sky Stacker TIFF files compatible with this specification.

Han

**Comment by perdrix52** [comment]
So when are you starting to write the code changes?

**Comment by han-k59** [comment]
I program in Pascal but I can't help you with C or something similar.

In pinciple it simple. The TIFF describtion string has to be filled with the FITS header. Each line ends with a CR+LF or LF. That's all. I assume it easy for you or somebody else. Is it? 

Han

**Comment by perdrix52** [comment]
It's not likely for personal reasons that I'll be able to do anything in the way of DSS development until (probably) mid-year :/

**Comment by han-k59** [comment]
Okay. At the moment four program are going to support it. This take times.

**Comment by han-k59** [comment]
One remark. For DSS as a stack program the relevant part is to read the header in the TIFF describtion tag containing the exposure, gain, date/time, filter. sensor temperature etc .....

**Comment by perdrix52** [comment]
It already does

**Comment by han-k59** [comment]
Detect how and which standard? mMta tags from DSLR cameras?

**Comment by han-k59** [comment]
For raw files that is not a problems but how get the information from ZWO, QHY SBIG, Atik and other camera suppliers other then using FITS files?

**Comment by perdrix52** [comment]
Close added to Where Next
