### ISSUE TITLE
Add support for mono-modded DSLR's

### ISSUE THREAD

**Issue by zfedoran** [deepskystacker/DSS#14]
For those of us who own color DSLRs that have been converted to monochrome, it would be nice to be able to process the RAW images without the debayer functions getting called. 

Currently, the workaround is to export tiff files with `dcraw -E -4 -T <filename>` then load those into DSS.

**Comment by perdrix52** [comment]
Thanks for the suggestion, Dave

**Comment by perdrix52** [comment]
Closing - issue added to "Where next"
