### ISSUE TITLE
Picture list column disappeared and cannot put back

### ISSUE THREAD

**Issue by williamli9300** [deepskystacker/DSS#145]
While I was attempting to sort images by Sky Background, DSS froze and then the column disappeared and will not return. A reinstall does not solve the problem, a complete deletion of the program and configs is required to bring it back. It would be nice if it were possible to right-click the column header row and enable/disable columns, as that would allow them to be refreshed in the case of something like that.

**Comment by perdrix52** [comment]
Can I suggest you ask about this problem on the mailing list at groups.io - I'm pretty sure there's a way to get columns back
