### ISSUE TITLE
5.1.0 beta1 is a debug build

### ISSUE THREAD

**Issue by zyw80** [deepskystacker/DSS#154]
Can't run this version without the debug redistributables

**Comment by perdrix52** [comment]
Yes absolutely it is a debug build - deliberately.  It also includes all the necessary .pdb files to allow debugging.

If the version you installed fails to run DeepSkyStacker (just closes immediately), please download the setup again (I have fixed that).

You cannot run it without having the Qt dlls. etc.

**Comment by perdrix52** [comment]
I will release the setup as a release build.

David
