### ISSUE TITLE
DSS hangs, then produces monochrome images

### ISSUE THREAD

**Issue by cdavila58** [deepskystacker/DSS#160]
I am using RAW image files from a Nikon z6 ii. When I stack a single image, I get faithful reproductions of the RAW images seen in other applications like Light Roo0m, as well as DSS' rendering of the individual light frames. The histograms for the RGB channels on the single image stack look different as they should be. However even when I stack two images, DSS will hang during "Computing Final Picture (Average)", the window says "not responding". After several minutes it will recompute the average and quickly produce a final picture, however it is completely monochrome, the RGB channel histograms are identical and the average looks completely monochrome, unlike the stack of single images. I am stacking just light frames.

**Comment by perdrix52** [comment]
Please report any issues on the DeepSkyStacker group at groups.io
