### ISSUE TITLE
5.1.0 Beta 2 Endless MessageBox loop after deleting file a file

### ISSUE THREAD

**Issue by OldFriendEr** [deepskystacker/DSS#161]
When deleting already registered file via file explorer, back in DSS trying to click on that file will generate an error message, closing it will open the same error again. 

Expected behavior is, getting the error once and removing that file from the list.

**Comment by perdrix52** [comment]
Patient: It hurts if I do that
Doctor: Don't do that!

Seriously though if you want to delete a file you can right click on it in the image list.

I'll take a look to see if there's an easy way to remove the file from the list in this case

D.

**Comment by perdrix52** [comment]
If put a fix into Beta 3 that will complain if a file is deleted outside DSS.  It won't remove the line from the file list, but you can press the Delete key to do that.
