### ISSUE TITLE
Reference Image did not work without checked checkbox

### ISSUE THREAD

**Issue by steve-shooty** [deepskystacker/DSS#168]
I tried to stack some mono images, the reference image must be checked in in the column 'path' for **each** stacked channel. If not checked in it does not affect the orientation to the reference. The orientation relates to the first in the row (filtered by 'Score') picture. 
Do i any wrong?

**Comment by perdrix52** [comment]
There can only be one reference image and it applies to all groups.  It’s either the one you mark by right clicking the row and selecting “Use as reference frame” or the one with the highest score.

 

DSS can’t stack multiple channels at once.

 

From: steve-shooty ***@***.***> 
Sent: 05 March 2023 00:43
To: deepskystacker/DSS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deepskystacker/DSS] Reference Image did not work without checked checkbox (Issue #168)

 

I tried to stack some mono images, the reference image must be checked in in the column 'path' for each stacked channel. If not checked in it does not affect the orientation to the reference. The orientation relates to the first in the row (filtered by 'Score') picture.
Do i any wrong?

**Comment by steve-shooty** [comment]
Hy pedrix52,
i do it so. I tested it today with 4.2.6 and here is all fine and each stacked channels orientated by the reference image. With the newest version it referring how i write, it don't refer by the checked image.

**Comment by perdrix52** [comment]
Please take this to the mailing list

**Comment by perdrix52** [comment]
Hi again, to subscribe please send an email to 	DeepSkyStacker+subscribe@groups.io 

Once you've done that, please report your problem with as much detail as possible to allow us to recreate it by sending an email to DeepSkyStacker@groups.io 

Thanks
David
