### ISSUE TITLE
Drop files in a group tap springs automaticly to 'Main-Group' tap back

### ISSUE THREAD

**Issue by steve-shooty** [deepskystacker/DSS#169]
After you take some files via drag and drop in a group tap the view jumps back to the 'Main-Group' tap. It does no matter what group tap it is.

**Comment by perdrix52** [comment]
Oh I do wish you’d been testing the Beta code …

 

From: steve-shooty ***@***.***> 
Sent: 05 March 2023 08:44
To: deepskystacker/DSS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deepskystacker/DSS] Drop files in a group tap springs automaticly to 'Main-Group' tap back (Issue #169)

 

After you take some files via drag and drop in a group tap the view jumps back to the 'Main-Group' tap. It does no matter what group tap it is.

**Comment by steve-shooty** [comment]
Hi, yes i do. I test it with too 4.2.6 and here it is ok. :-9

**Comment by perdrix52** [comment]
No it wasn't OK with the Beta code - anyway I have fixed it and refreshed the 5.1.0 release - just DL it again and reinstall

PLEASE DO NOT RAISE PROBLEMS HERE _ DO SO ON THE MAILING LIST
