### ISSUE TITLE
Properties of multiple files 5.1.0

### ISSUE THREAD

**Issue by dudfunk** [deepskystacker/DSS#170]
In 4.6.2, I was able to set properties of multiple files by Select All>Right click>Properties.  Now when I right click there is no Properties.  Is there a different way to set/view properties of multiple files in 5.1.0?

**Comment by perdrix52** [comment]
Please raise this issue on the DeepSkyStacker mailing list at groups.io to discuss the need for setting properties on multiple files.

For a single file: double click on any of the cells outlined in blue (Type, ISO/Gain, Exposure) to edit

Thanks, David
