### ISSUE TITLE
DSS 5.1.0 final processed images are gray

### ISSUE THREAD

**Issue by dudfunk** [deepskystacker/DSS#171]
Not sure if I'm missing something here.  My final stacked images appear to be in color in the preview in DSS, but when I open the TIF, regardless if it is the autosave file or the file that comes from the Save Picture File As... function, the image is gray.  I opened the file in Photoshop to see if there is color data there, while I can see the three RGB channels, they're all grey.  The histogram won't even show a graph.  It's weird because in DSS I can see color in the preview.
![image](https://user-images.githubusercontent.com/45182947/223442056-a644fc7f-2dfc-43eb-ae60-cff933457d5e.png)
The RAW settings are identical to what I had in 4.6.2 which did not have this issue.

**Comment by dudfunk** [comment]
Sorry for the post, but it looks like the color data is in fact in the file I just have to work harder to get them right.  Not sure why though.  Previously the stacked image would show some color and I'd work on it from there in PS.  But now the image appears completely grey.
![image](https://user-images.githubusercontent.com/45182947/223443663-2f3c7221-802b-448f-8370-5ecc1c2d8779.png)

**Comment by dudfunk** [comment]
Again I apologize for this whole post, I had to select Apply settings to output image.  Closing.

**Comment by perdrix52** [comment]
Please please do not report issues here.  Report then on the mailing list as requested.
