### ISSUE TITLE
Computing the number of stars is seriously slow/impossible in 5.10

### ISSUE THREAD

**Issue by maboleth** [deepskystacker/DSS#172]
On 4.2.6 the calculation speed is almost instant (literal 1-2sec).

On 5.1.0 it's over 3 minutes for same files to reach 74% then went on several minutes to go to 86%.

Then I closed the app as this went over 5 minutes.

It does say "4 Processors used" - not sure why since all are checked to be used.]

Ryzen 3700
32gb ram
5500 GPU AMD
Windows 11 PRO

**Comment by perdrix52** [comment]
Can you not read - report problems on the mailing list

**Comment by perdrix52** [comment]
Fixed in 5.1.3
