### ISSUE TITLE
Confirmed bug reports from DeepSkyStacker mailing list at groups.io

### ISSUE THREAD

**Issue by perdrix52** [deepskystacker/DSS#174]
- [x] Superpixel mode - at least with FITS images - stacked output is shown with image taking only top right corner of image area.
 Supporting data https://www.dropbox.com/sh/uq0cgoqujkhxd0i/AACN7i72xmOjrMlfEOloaIXua?dl=0
 Detlef says: bug does not appear if you define a whole size custom rectangle before stacking. So I suppose that somewhere in the code the information on halfwide internal frames got lost.
Fixed on March-09-2023: Bug in function IsFitsSuperPixels() in FITSUtil.cpp.

**Comment by astrodet** [comment]
Thanks to Martin for the fix. I will wait for DSS 5.1.1 !
