### ISSUE TITLE
Enabling Super pixel mode crops image to upper left 1/4

### ISSUE THREAD

**Issue by Nimleth** [deepskystacker/DSS#184]
Hi,

when you enable super pixel mode in the recommended settings for narrow band imaged, the resulting image after stacking is cropped to the upper left 1/4 of the total image.
I've seen discussions on this that it only happened intermittently or that its gone after resetting to the default values but it happens every time that super pixel is enabled.

DSS version 5.1.3. (Didn't have  this issue before, I think that was 4.2.6)

Rgds,
Dennis

**Comment by perdrix52** [comment]
I promise this will get looked at once we're through the current set of changes...
