### ISSUE TITLE
Picture list column does not show up!

### ISSUE THREAD

**Issue by FlashGordon3140** [deepskystacker/DSS#185]
After upgrading to version 5.13 on Mac M1 Paralel Desktop and Window 11, le picture list pane on the left of DSS window does not show up, so it is impossible to do anything.
**Provide necessary data to reproduce the problem**
Most problems with DeepSkyStacker will need you to upload a minimal set of files that allow the problem to be recreated including a dssfilelist to a file sharing site.  Obviously if the problem can be recreated with any (or no data) such as a UI problem then we don't need that.

![image](https://github.com/deepskystacker/DSS/assets/70107391/75fc7090-3edd-4c7b-8041-def436b7d059)

On previous 4.2.6 version, same configuration I do not have the issue!

**Comment by perdrix52** [comment]
I don't know how you ended up with the Explorer Bar detached and not visible, but I believe I know how to fix it.

Open regedit, and navigate to HKCU/Software/DeepSkyStacker/DeepSkyStacker5/MainWindow and delete that key.

The start DSS. that should resolve the problem.

**Comment by FlashGordon3140** [comment]
Great, it is working! Many thanks for your help so quickly it is greatly appreciated.....

Just a note. It is not 

HKCU/Software/DeepSkyStacker/DeepSkyStacker5/MainWindow


but

HKEY_CURRENT_USER/Software/DeepSkyStacker/DeepSkyStacker5/MainWindow

But that's fine...

Again many thanks!


Kind regards,

=-= Jacques Masson =-=

**Comment by perdrix52** [comment]
Sorry, I though everyone would recognise HKCU as an abbreviation for HKEY_CURRENT_USER

**Comment by FlashGordon3140** [comment]
no....😩
