### ISSUE TITLE
Translate DeepSkyStacker in another language

### ISSUE THREAD

**Issue by bob-zebedy** [deepskystacker/DSS#186]
I want to translate DeepSkyStacker in Simplified Chinese language. Is it by the steps in http://deepskystacker.free.fr/english/localization.htm?

**Comment by perdrix52** [comment]
No it isn’t.  Right now the translation is a mixture of Qt Linguist and editing .rc files  Once the porting to Qt is complete I will happily accept your proposal to translate DSS to mainland Chinese.   But right it would an exercise in frustration for you.

David

**Comment by perdrix52** [comment]
Unfortunately the DeepSkyStacker website is now sadly out of date and isn't owned by me.

**Comment by deplives** [comment]
> No it isn’t. Right now the translation is a mixture of Qt Linguist and editing .rc files Once the porting to Qt is complete I will happily accept your proposal to translate DSS to mainland Chinese. But right it would an exercise in frustration for you.
> 
> David

So currently I need to wait for porting QT to finish.

**Comment by perdrix52** [comment]
If you contact me direct (david.partridge@perdrix.co.uk) I can send you the Qt Translation Source (.ts) files for translation to Simplified Chinese.   If you also want the Traditional Chinese files for comparison, just ask.

**Comment by perdrix52** [comment]
Yes it is translated to French and many other languages
