### ISSUE TITLE
Can't install DSS

### ISSUE THREAD

**Issue by itsmehere2** [deepskystacker/DSS#187]
Hi,

I've just downloaded the latest version of DSS 5.1.3 and during installation I get following message:

Error opening file for writing:
C:\Program Files\DeepSKyStacker\DeepSkyStacker.exe
Click abort to stop the installatiom
Retry to try again, or
Ignore to skip this file.

Can you please advise. It looks like the installation has un-installed the previous version so I am without DSS now.

Thankyou,
Jeff

**Comment by perdrix52** [comment]
To install into Program Files you need to be a member of the Administrators group.

Are you?

**Comment by itsmehere2** [comment]
Hi,

Thankyou for the quick response.
Its on a personal laptop belonging to me.

**Comment by perdrix52** [comment]
That doesn't necessarily mean that the user you are logged with has admin rights.   

I assume you cancelled the installation and tried again and it failed in the same way?

If so, try this:  navigate to C:\Program Files and delete the DeepSkyStacker folder.

Then retry the installation.

**Comment by itsmehere2** [comment]
I tried several times with no success, I've never had this with DSS before its always been fine so I think the admin rights are ok.

I've managed to get 5.5.1 working again, but not sure how as it doesn't appear in the program list?

I will try the method you suggest.

Thankyou for the advice,
Jeff

**Comment by perdrix52** [comment]
If you are still having problems I suggest we set up a windows assistance session.

**Comment by perdrix52** [comment]
There is no 5.5.1 release - there's a 4.2.6 release, and then there's 5.1.3

**Comment by itsmehere2** [comment]
Excellent, thankyou David, I'll let you know.
Cheers,
Jeff

**Comment by itsmehere2** [comment]
My mistake I meant 5.1.1

**Comment by perdrix52** [comment]
I'd advise against 5.1.1 - it and 5.1.2 are a bit broken

Use control panel programs and features to completely uninstall 5.1.1 reboot and then try 5.1.3

**Comment by itsmehere2** [comment]
Right ok. I'll try that before your other solution.

Thankyou for your excellent support at the weekend, it is much appreciated.
Jeff

**Comment by perdrix52** [comment]
Closed as no further input from user
