### ISSUE TITLE
Can't open again the "Explorer" bar (left panel)

### ISSUE THREAD

**Issue by mishavoloshchuk** [deepskystacker/DSS#188]
I tried to undock the "Explorer" bar [DeepSkyStacker 5.1.0 Release, item 2](https://github.com/deepskystacker/DSS/releases/tag/5.1.3#:~:text=The%20image%20list%20can%20now%20be%20undocked%20from%20the%20bottom%20of%20the%20Stacking%20panel%20so%20that%20it%20operates%20as%20a%20separate%20window.%20The%20%22Explorer%22%20bar%20(left%20panel)%20can%20also%20be%20undocked.)
![DeepSkyStacker](https://github.com/deepskystacker/DSS/assets/54890360/393a252d-8281-4434-b9ab-2c270f5f2c3c)
but then I wanted the panel back to its standard position, I pressed the Alt + F4 and the panel was closed but it didn't appear in its normal position. Now I can't open the bar again (reinstallation didn't help).

**To Reproduce**
1. Click the "Undock" button (first image)
2. Click at the top of the window that appears (to focus on it)
3. Press Alt + F4

**Expected behavior**
The "Explorer" bar should have appeared on its normal position on the left of the window after pressing Alt + F4

My DeepSkyStacker version: 5.1.3

Now the program looks like this:
![Знімок екрана 2023-07-31 193342](https://github.com/deepskystacker/DSS/assets/54890360/dc2d94b8-7be6-47df-9e5e-2722964fea5e)

**Comment by perdrix52** [comment]
Known problem - fixed in development version.  To get the panel back delete Registry key:
HKEY_CURRENT_USER/Software/DeepSkyStacker/DeepSkyStacker5/MainWindow

To re-dock, you drag/drop or double click title bar of undocked window, NOT Alt-F4

**Comment by mishavoloshchuk** [comment]
Thank you for your reply! It helped😃
