### ISSUE TITLE
FITS Header OBSERVER truncated

### ISSUE THREAD

**Issue by dkracht** [deepskystacker/DSS#195]
When writing the result file with a FITS header, DSS truncates the value of "OBSERVER" after the first blank. Pls. ise the full content of that value string.

**Comment by perdrix52** [comment]
Please raise this and the other issues you opened on the groups.io mailing list for dicussion and prioritisation

**Comment by perdrix52** [comment]
I will shortly release DSS 5.1.4 Beta 1 which I hope should address your concerns.  You'll still need to use your own propagated keyword list ...
