### ISSUE TITLE
DSS5.1.5 - Error Message "The System canno find the path specified"

### ISSUE THREAD

**Issue by SiriusLux2023** [deepskystacker/DSS#202]
**Check the Wiki**
Before you report any issues it is worth checking the DeepSkyStacker Wiki: <https://groups.io/g/DeepSkyStacker/wiki>

If you aren't a member the DeepSkyStacker mailing list, please join by sending an email to:

DeepSkyStacker+subscribe@groups.io

Once you have successfully joined the mailing list please report the problem on the mailing list by sending an email to:

DeepSkyStacker@groups.io

Your email should contain the following information:

**Describe the bug**
A clear and concise description of what the bug is.  Please specify the version of DeepSkyStacker and if relevant whether the problem is with DeepSkyStacker Live or DeepSkyStacker Command Line

**Provide necessary data to reproduce the problem**
Most problems with DeepSkyStacker will need you to upload a minimal set of files that allow the problem to be recreated including a dssfilelist to a file sharing site.  Obviously if the problem can be recreated with any (or no data) such as a UI problem then we don't need that.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Here's my issue, when I try to launch DSS I get the Error Message: "The System cannot find the path specified".
Here's my working environment:
OS: Windows 10 pro 64 bit,
DSS Version: 5.1.5
DSS installed in the following path: "C:\Program Files\DeepSkyStacker"
The drives: 
SSD with volume C: (for OS and some programs) 313GB free and volume D: (for programs) 138GB free
HD with volume E: (for data) 1.18TB free
No matter whether I try to launch DSS 5.1.5 from the start menu or through a double-click on "DeepSkyStacker.exe" the error message appear. This was not the case with version 5.1.3.
I frankly don't know what to do.

**Comment by perdrix52** [comment]
So you didn't do as you were asked (which is to post your problem to the mailing list)!!!?????

So why should I provide support when you were asked to report it on the mailing list as VERY CLEARLY instructed above.

Please do as you were asked.

Also please provide a display of the desktop shortcut for DeepSkyStacker (does it point to D: or C:)

Assume the message is a windows popup message.  Please attach a screen shot to your post to the mailing list of the error message.
