### ISSUE TITLE
DeepSkyStacker broken on non latenic letter user

### ISSUE THREAD

**Issue by EAZYBLACK** [deepskystacker/DSS#203]
**Check the Wiki**
Before you report any issues it is worth checking the DeepSkyStacker Wiki: <https://groups.io/g/DeepSkyStacker/wiki>

If you aren't a member the DeepSkyStacker mailing list, please join by sending an email to:

DeepSkyStacker+subscribe@groups.io

Once you have successfully joined the mailing list please report the problem on the mailing list by sending an email to:

DeepSkyStacker@groups.io

Your email should contain the following information:

**Describe the bug**
Open DeepSkyStacker and u get ???????????????? error if your username has non latenic alphabet letters

**Provide necessary data to reproduce the problem**
create a user with non english (e.g greek) letters
install deepskystacker and see

**To Reproduce**
1. Create a user with non latenic letters
2. Open deepskystacker
3. See error

**Expected behavior**
Deepskystacker should work normally

**Screenshots**
![image](https://github.com/deepskystacker/DSS/assets/68810731/cba4c100-7f38-446c-af60-af374c89929e)

**Additional context**
I had this issue on my pc i edited registry and renamed my user from greek to english letters

**Comment by perdrix52** [comment]
What part of "please report the problem on the mailing list" did you not understand?  Please report the problem ON THE MAILING LIST, NOT HERE!  Please also provide full details of the DeepSkyStacker release you are using.

**Comment by EAZYBLACK** [comment]
oh sorry

**Comment by perdrix52** [comment]
No a big problem but ...

Also the message I got read: The system cannot find the path specified.  

Was the what you received?  If not I want to know more (but on the mailing list please).

**Comment by perdrix52** [comment]
https://groups.io/g/DeepSkyStacker/topic/special_build_of/103399218

**Comment by perdrix52** [comment]
If you do install the special build please post to the mailing list to report success or failure, NOT HERE!
