### ISSUE TITLE
Error when attempting to select a Comet in a picture

### ISSUE THREAD

**Issue by rpassblgrd** [deepskystacker/DSS#205]
**Describe the bug**
I'm using DSS 5.1.5. I have been attempting to stack images of 12P/Pons-Brooks. I've managed to get MOST of the comet references marked but, when I attempt to make some of them (in this case, Luminance frames), I'm getting an error "Exception ZInvalidRequest thrown from C:\Users\amonra\Documents\GitHub\DSS\DeepSkyStackerKernel\GrayBitmap.cpp Function: CGrayBitmapT<double>::CheckXY() Line: 61

The following expression must be true, but evaluated to false: IsXYOk(x, y)". So, it appears that there is a direct reference to somebody's code base within the released version of the code.

**Provide necessary data to reproduce the problem**
Basically, I have some comet data from an 800mm scope with an ASI183MM camera. MOST of the frames seem to not have any issue with identifying the comet but, a few of them do. I can provide a 

**To Reproduce**
1. I can provide the DSS List and a few of the Luminance files if that'd help. I can repeat the problem w/ the list, 3 FITs files, and, of course, the info.txt files associated with them.
2. I already selected the comet on Red, Green, and Blue channels (2 through 4), Tab 0 has Darks and Bias, Tab 1 is Luminance
3. I started selecting the position of the comet in each frame.
4. When I attempt on the 3rd frame down, I get the error.

**Expected behavior**
I was expecting to be able to choose the comet by either clicking on it or doing Ctrl-Shift and then clicking on it but, either approach leads to the error message..

**Screenshots**
Screen shots attached.

**Additional context**
Will provide a DSS File List w/ 3 FITS files if somebody will give me an e-mail to share to in DropBox since the FITS files are too big.
![DSS_Error](https://github.com/deepskystacker/DSS/assets/164059882/9ce41d07-056a-4a09-965b-df5419994827)
![DSS-screenprint](https://github.com/deepskystacker/DSS/assets/164059882/bab1c96e-2b62-412a-8d2d-f72cdd385709)

**Comment by perdrix52** [comment]
Please report this on the mailing list as requested and provide a link to a file sharing site containing the files necessary to reproduce the problem

**Comment by rpassblgrd** [comment]
I would be happy to "provide a link" if somebody will TELL ME HOW to do it from DropBox. :-) It's all ready to go, just don't know how to get it to you in a way that'll be useful to you. I have no other file sharing sites. I have posted the same content on the mailing list minus the pictures since I didn't see a way to attach those.

**Comment by perdrix52** [comment]
Thanks closing this here.  Will follow up on mailing list.  David
