### ISSUE TITLE
To do May 2024

### ISSUE THREAD

**Issue by mtoeltsch** [deepskystacker/DSS#206]
Martin Toeltsch
This list is just to manage the open issues (18-May-2024).

- [x] Append a number to output file not working.
       [Link](https://groups.io/g/DeepSkyStacker/message/31289)
- [x] If a colour TIFF file contains CFA exif data, it's interpreted as Bayer CFA. This causes a crash.
       [Link](https://groups.io/g/DeepSkyStacker/message/31323)
- [x] Adding a new file-group sometimes results in wrong group name.
- [x] The saved file list sometimes contains too few groups or wrong group names.
- [x] The entire EditStars functionality (including edit comets) is buggy.
       The green rectangles jump around in a weird manner, after some time DSS crashes.
       [Link to mailing list](https://groups.io/g/DeepSkyStacker/message/31369)
- [x] The magenta circle around the comet stays even after removing the image file.
       This seems to be a severe problem, as [Bruce Sobut reports here](https://groups.io/g/DeepSkyStacker/message/31441).
       DSS is caught in comet-mode after loading a file-list with comet, calculating offsets fails (according to Bruce). The only way out is to load a file-list without comet.
      However, Bruce used a file-list with "no alignment" set, which was the reason for setting all offsets to "0.0". Also all other problems reported by him were user errors (he mistakenly defined a comet in one of his light-frames, etc.).
- [ ] Occasional crashes in Align RGB Channels.
       [Link to mailing list](https://groups.io/g/DeepSkyStacker/message/31366)
       October 2024, MT: I was still not able to reproduce it.
- [ ] ~Bruce Sobut reported still an inconsistent result file name (Autosave instead of `<file list name>`.~
      ~[Link to mailing list](https://groups.io/g/DeepSkyStacker/message/31372)~
     _Bruce was not able to reproduce it, nor was I._
- [x] 2 instances of DSS open, save a file-list into a directory, the other instance also defaults to this directory, even with unrelated projects.
       [Link to mailing list](https://groups.io/g/DeepSkyStacker/message/31287)
- [x] When saving a file list after modification, there is no default file name in the 'explorer' window. I have to click on the previously saved version and modify from there.
- [ ] Comet+stars stacking: Remove remaining faint star trails in/behind the comet tail.
- [x] Bruce Sobut gets a reproducible crash (STACK_OVERFLOW) when registering a JPG file.
      This is his log file: [DSSTrace](https://github.com/deepskystacker/DSS/files/15373740/DSSTrace_2024-05-19T20-12-49Z.log)
      Unfortunately, he cannot find the JPG file anymore.
      Fix: It was caused by a call to Progress2() from other than the main thread. Fixed in V 5.1.6.
- [x] Request for lower registration threshold than the 2%
      [Link to request on mailing list by André Holzmeister](https://groups.io/g/DeepSkyStacker/message/31378)
      User Jesse Goldba provided an example [On Dropbox](https://www.dropbox.com/scl/fi/ibsjfb6mhz618ae5dxm9u/DSSGroup.zip?rlkey=rbpyhd7d0gcjor4tyoxy6nvi5&dl=0)
- [x] Request by Bruce Sobut to insert a '-' between fileListFile and the increasing number.
- [ ] Request by Bruce Sobut: When loading a file list when files already loaded, a reminder that files are loaded or a "Do you wish to clear existing files?" [Link to request](https://groups.io/g/DeepSkyStacker/message/31426)
- [x] Multiple reference frames can be selected in the file listing. 
- [ ] ~Default file type for picture files shall be RAW instead of PICTURE files.~
     _This has been rejected by the community._
- [x] ThreadLoader and ImageLoader are not concurrency-safe. 
      This results in different pictures stored under identical (thus wrong) file-names in the image cache. Hence, it's filled up with unaccessible cache entries.
- [x] Make the registration process independent of a user-defined threshold.
       Possibilities are: 
       Get rid of the threshold alltogether and find an algorithm which does not need a threshold.
       Keep an internal threshold but hide it from the user and implement a little optimisation algorithm to auto-find a good threshold.
       For the moment, we have chosen to use an "auto-threshold" optimisation algorithm.
- [x] Bug: AVX code does not compute the stacking result properly with a custom rectangle.
- [x] Bug: (1) Display a light frame. (2) Click on the Custom Rectangle button. (3) Draw a rectangle.
        Result: The rectangle disappears immediately after drawing it.
        Workaround: Click on Edit Stars, then click on Custom Rect. Then it works.
        Fix: The Qt connect() function is called multiple times for the according signal/slot. So it must be called with Qt::UniqueConnection.

**Comment by perdrix52** [comment]
Thanks Martin – I may even find some time in June to work with you to issue a bug fix release.

 

The first one you report here – that’s that first I have heard of it.

 

From: Martin Toeltsch ***@***.***> 
Sent: 18 May 2024 08:30
To: deepskystacker/DSS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deepskystacker/DSS] To do May 2024 (Issue #206)

 

Martin Toeltsch
This list is just to manage the open issues (18-May-2024).

*	[ ] The entire EditStars functionality (including edit comets) is buggy.
The green rectangles jump around in a weird manner, after some time DSS crashes.
Link to mailing list <https://groups.io/g/DeepSkyStacker/message/31369> 
*	[ ] Occasional crashes in Align RGB Channels.
Link to mailing list <https://groups.io/g/DeepSkyStacker/message/31366> 
*	[ ] Bruce Sobut reported still an inconsistent result file name (Autosave instead of .
Link to mailing list <https://groups.io/g/DeepSkyStacker/message/31372> 
This is low priority, as Bruce was not able to reproduce it, nor was I.
*	[ ] 2 instances of DSS open, save a file-list into a directory, the other instance also defaults to this directory, even with unrelated projects.
Link to mailing list <https://groups.io/g/DeepSkyStacker/message/31287>

**Comment by perdrix52** [comment]
In Comet editing mode the Green rectangle snaps to existing stars unless you use the Shift key which allows you to click anywhere. 

 

David

**Comment by mtoeltsch** [comment]
> In Comet editing mode the Green rectangle snaps to existing stars unless you use the Shift key which allows you to click anywhere. David

If you test it with that file:

https://groups.io/g/DeepSkyStacker/attachment/31369/1/C-2023%20A3%20_Tsuchinshan-ATLAS__2024-05-16_22-23-47_60.00s_ISO200_0.00_0030.nef

you'll notice that the green rectangle snaps e.g. to a star in the upper left corner while the mouse is in the bottom right part of the image. If you then mark it as a comet, it won't let you un-mark it anymore. With other stars, it works better, so it's a mixture of "normal" and "weird" behaviour. 
After some marking/un-marking actions, DSS crashes with an EXC_ACCESS_VIOLATION, because from the vector EditStars::stars the item with index 2 shall be erased while the vector has a length of only 2.

**Comment by perdrix52** [comment]
Hmm – that’s not so good ☹

**Comment by mtoeltsch** [comment]
BTW, it's exactly the same in DSS 4.2.6, so that bug is not new.

**Comment by perdrix52** [comment]
Aha!  At least I didn’t introduce it when I ported the code to Qt 😊

**Comment by mtoeltsch** [comment]
I'm in the middle of the work to debug the comet editing mode. 
Question: There's a global `bool g_bShowRefStars = settings.value("ShowRefStars", false).toBool();` 
It's always false, and in DSS there's no setting whatsoever to turn on a "Show Reference Stars" option. 
There's a lot of code depending on this bool g_bShowRefStars, which is actually dead code. Can I remove it?

**Comment by perdrix52** [comment]
You can set it using the registry editor 😊

 

I was AFAICT intended for developer debugging…

 

David

**Comment by mtoeltsch** [comment]
I was able to fix the "rectangle jumping around" issue, it was a serious bug in function `FindNearestStarWithinDistance()`.
But still the logic is incorrect, e.g. when removing one star, the star count falls from 12 to 9. After some time, there's still an access violation.
I'll continue to search for the problem, but the function EditStars::draw() is rather complex and obscure.

**Comment by mtoeltsch** [comment]
I fixed the entire EditStars and CometMode issues. I streamlined the whole EditStars class to a large extent, but left all the old code in - just commenting it out what's not needed anymore.

**Comment by mtoeltsch** [comment]
But now I notice that there is an almost 100% code duplication in file ImageSinks.cpp, the class is CEditStarsSink.
I did not change anything in ImageSinks.h/.cpp or so. 
Question: What's the purpose of these ImageSink stuff? Do you think there's a possibility to remove the whole code duplication by e.g. just re-using the EditStars class for this?

**Comment by perdrix52** [comment]
The ImageSinks code is almost ready for deletion.   It is the old code, and I think there's one small piece of code that still uses it.
