### ISSUE TITLE
Display issue with font bigger than default size

### ISSUE THREAD

**Issue by Cyrille28** [deepskystacker/DSS#212]
Hello,
The display of the first bloc is not ok when using system display at 150% instead of 100%
![dss display bug](https://github.com/user-attachments/assets/1c09a55a-e214-43d8-a001-8b170a1f2c28)

**Comment by perdrix52** [comment]
PLEASE, PLEASE follow the instructions and report problems to the mailing list not here

**Comment by perdrix52** [comment]
I cannot reproduce this problem with the current development build which well be release soon (5.1.7)
