### ISSUE TITLE
Improving Overall UI

### ISSUE THREAD

**Issue by sakhadib** [deepskystacker/DSS#216]
The current UI of DeepSkyStacker feels outdated and lacks a modern, user-friendly design. Many elements are unintuitive, making it challenging for users to navigate and utilize the full range of features effectively. This issue impacts both new users trying to understand the workflow and experienced users aiming for efficiency. I propose enhancements to improve usability and aesthetics.

**Provide necessary data to reproduce the problem**
The UI issues are persistent across all versions of DeepSkyStacker, and they affect both the primary application and the Live variant. The visual layout and functionality limitations are visible without any specific data or configurations.

**To Reproduce**
1. Open DeepSkyStacker.
2. Attempt to navigate through menus and options, particularly for loading and processing images.
3. Observe how the layout and design impact ease of use and clarity.

**Expected behavior**
An updated, intuitive interface that aligns with current design standards, making the user experience smoother, clearer, and more visually engaging. Improvements could include reorganization of menus, a more accessible layout, and an updated color scheme.

**Additional context**
Revamping the UI would make DeepSkyStacker more accessible and appealing to a broader audience, enhancing user satisfaction and efficiency.

**Comment by perdrix52** [comment]
Gee a lot of criticism, and no clear suggestions for how to improve the UI, just a lot of hand waving. Would you like to fork the project and re-work the UI - I'd expect about two man years of work...
