### ISSUE TITLE
blurred image

### ISSUE THREAD

**Issue by Veronica0508** [deepskystacker/DSS#217]
**Check the Wiki**
Before you report any issues it is worth checking the DeepSkyStacker Wiki: <https://groups.io/g/DeepSkyStacker/wiki>

If you aren't a member the DeepSkyStacker mailing list, please join by sending an email to:

DeepSkyStacker+subscribe@groups.io

Once you have successfully joined the mailing list please report the problem on the mailing list by sending an email to:

DeepSkyStacker@groups.io

Your email should contain the following information:

**Describe the bug**
A clear and concise description of what the bug is.  Please specify the version of DeepSkyStacker and if relevant whether the problem is with DeepSkyStacker Live or DeepSkyStacker Command Line

**Provide necessary data to reproduce the problem**
Most problems with DeepSkyStacker will need you to upload a minimal set of files that allow the problem to be recreated including a dssfilelist to a file sharing site.  Obviously if the problem can be recreated with any (or no data) such as a UI problem then we don't need that.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by perdrix52** [comment]
**_>list please report the problem on the mailing list_**

**Comment by perdrix52** [comment]
Hint - look at Stacking Settings/Alignment and try different alignment options

**Comment by Veronica0508** [comment]
> Hint - look at Stacking Settings/Alignment and try different alignment options

ok thanks
