### ISSUE TITLE
Option so that FITTs are stored and loaded “vertically mirrored”

### ISSUE THREAD

**Issue by NGC6888** [deepskystacker/DSS#31]
Implement a Checkbox in “Options” >> “Raw/FITTS DPP Settings”, so that FITTs are stored and loaded “vertically mirrored”.
The Setting should be stored permanently in registry.
The reason is, DSS writes and reads FITTS-files vertically mirrored.
Fitswork for example has the same bug. (Some years ago the bug propagated in some Windows software because they copied it from an old version of Maxim).
There is only one correct vertical FITS orientation: the one used by all professional astronomy software. Correct software is Pixinsight and Astroart.

Thank You
Norbert

**Comment by perdrix52** [comment]
Norbert, I just ran a small stack using DSS and saved the output to a FITS file which I then opened in FITS Liberator which is probably the canonical FITS tool.   It displayed in the same orientation that DSS displayed it to me which suggests that we are doing if right.

**Comment by NGC6888** [comment]
I just downloaded FitsLiberator3 and checked the behaviour.
FitsLiberator opens a *.FIT File correctly, Fitswork and DSS opens it vertically mirrored.

**Comment by NGC6888** [comment]
![fit_test1](https://user-images.githubusercontent.com/38884636/39481094-8f74b482-4d6a-11e8-87fb-53ff6d23809e.JPG)

**Comment by NGC6888** [comment]
...because of comaptibility to Fitswork, I suggest a checkbox to set the correct behaviour as an "option".

**Comment by NGC6888** [comment]
[M42_small_2.zip](https://github.com/LucCoiffier/DSS/files/1964432/M42_small_2.zip)

You can try it with this Image...

**Comment by perdrix52** [comment]
That conflicts with my observations.  A fits file written by DSS is displayed by Liberator identically to the way we display it.    The reason it is shown with the horsehead in normal orientation in **your** FITS Liberator screen capture is that you have **clearly** ticked the "Flip Image" check box in the Liberator UI.

**Comment by NGC6888** [comment]
OK, interesting.
So normal orientation is "flipped", as this is default in Liberator after fresh install.
So who is right?
As Astroart (which I use for post processing) uses the Flip-Orientation, I have to manually flip the fits every time.
I still want to use DSS because the stacking results are very good and it's very intuitive to use.

This is also a concern of a friend who also uses this configuration and sometimes he forgets to flip.
(...so he publishes flipped images)

Greetings
Norbert

**Comment by NGC6888** [comment]
Also the same result with this Fits WebViewer:
http://www.clearskyinstitute.com/fits/fits.html
![image](https://user-images.githubusercontent.com/38884636/39487960-15921fc6-4d81-11e8-965d-863990ecac6a.png)

**Comment by NGC6888** [comment]
Acxording to:

> Given this, I would suggest that you are incorrect in your assertion. What makes you so sure the test images you provide are correctly oriented?

I had a discussion with the developer of Astroart.
He convinced me that the flip bug has its origin in a buggy lib form "Maxim" which was implemented in Fitswork. So he refused to modify "Astroart" for compatibility with fits-format as it is programed with correct fits specs.

Norbert

**Comment by NGC6888** [comment]
Appendix:
In Fitswork4, there is also the option for flipping a fits.
Standard is "checked", if unchecked, also Fitswork shows fits in "flipped orientation" as Astroart and Pixinsight does.

**Comment by perdrix52** [comment]
I will leave Luc to make the final call on this.  So far all you have proven to me is that different software does it differently.  Not any definitive proof of which is correct though.  Purely your assertions, and no disrespect to you - why should I believe you over other authorities?

**Comment by NGC6888** [comment]
Hello David,

Thank You for thinking about it.
I did not assume You make something wrong, I only have that problem, that I have two software developers who both think they do make everything correct and I want to use both software without need for a manual step (I also can forget) to get them work together.
Another solution could be my other suggestion #30, so I can open the autosave.tif in Astroart without need of saving it as fit a second time.

Thank You so far.

I also know that DSS is free of charge, so I appreciate you developing this project further.
Norbert

**Comment by NGC6888** [comment]
Hello,

Astroart7 64bit can load the "autosave.tif" now directly,
So it's not necessary to do here anything (for me), I simply do not use "fits"-format.

As for compatibility with Pixinsight, when you use PI, you also stack with PI...

Norbert

**Comment by perdrix52** [comment]
Added to "Where next" issue. Closing this
