### ISSUE TITLE
Add a color workflow for monochrome ccds

### ISSUE THREAD

**Issue by Hansi123456789** [deepskystacker/DSS#34]
Hi, could you add a color workflow for monochrome ccds?

I have an asi 1600 mm-cool monochrome ccd. DSS works with its monochrome files. 

But in the end, I only can get L,R,G,B black and white pictures from DSS.
Unfortunately, I must use additional tools like fitswork or the expensive pixinsight in order to combine them to a color image.

Could you add a mode for monochrome cameras to DSS?

One  should be able to group luminance, red, green and blue lights and flats and then DSS should automatically stack and combine them correctly to a color image.

Additionally, DSS may support false color imaging like the hubble pallette or other color schemes

**Comment by tonk777** [comment]
Very good request. This one should be a priority as DSS is (maybe) too focused on OSC cameras and regular monochrome CCD has been rather left out given its prevalence in AP.

The existing group feature should be the jumping off point for handling the calibration of L,R,G,B channels,

The addition of narrowband channels should also be considered. This should include options for the standard Ha, OIII, SII, NII named filters but should also include the ability to create custom named channels (e.g. I use CN, CO+ and C2 filters for comet imaging)

Finally (as mentioned above) to complete this feature there has to be a channel mixing tool. For example it could be modeled on Images Plus interface as this is quite simple (we would have DSS group(s) to output LRGB channel assignments each with 0 - 1 weightings). It would be nice to be able to do the channel mixing in (near) real time

**Comment by robertpascale** [comment]
I like this request, but I think there is an interim use case that might be beneficial.

1. When importing the images, use the FILTER to split the images in to groups (if you could name the groups to make it easier to identify, that would be a bonus). 
This would simplify having to go through and pull each sub type and put it in to different groups manually.

2. When stacking, I will select a reference image (in one group) and then stack all images in that 1 group (eg my Red filter) and save the image as my Red stack. 
Then, leaving the reference image the same, uncheck all the images in Group 1, select all the images in Group 2 (eg. Green filter), stack them to produce my Green stack.
Then rinse and repeat for Blue and H-alpha.

The above process is a bit of a click fest, interrupted by waiting for each stack to process, and is therefore error prone.

If the resulting process could all be done "at once", and then the autosave files could be named something like autosave<xxx><group-name(filtername)>. Then the resultant files could be dragged in to another program to combine and edit.

The above feature request is mostly within the scope of DSS as a file processing workflow enhancement, not so much as adding to the complexity image processing itself of combining the various channels to a single image (eg. in my use case, if you merged the RGB channels, there's be the left over luminance channel)

**Comment by perdrix52** [comment]
Where is the FILTER identification data coming from?  Is that something you are putting in the FITS header?

If yes, there's some hope ...

David

**Comment by robertpascale** [comment]
Hi David,

It's in the FITS Header - I reviewed them in FITS Liberator on the images I've taken over the last few nights using different software. 
There is also the image type information in there that could also assist with automatically sorting the image types on import. I'm not sure if there are enumerated in the standard somewhere, or it's all a bit free form depending on the software.

For the IMAGETYPE, for my images the enumeration is as follows in two different software packages:
`
CREATOR = 'Sequence Generator Pro v3.1.0.454' / Capture software
IMAGETYP= 'LIGHT   '
IMAGETYP= 'FLAT    '
IMAGETYP= 'BIAS    '
IMAGETYP= 'DARK    '

SWCREATE= 'Astro Photography Tool - APT v.3.82' / Imaging software
IMAGETYP= 'Light Frame'
IMAGETYP= 'Bias Frame'
IMAGETYP= 'Dark Frame'
IMAGETYP= 'Flat Frame'
`

For the FILTER, it's irrelevant really if it's enumerated or not - just use whatever is in there to group by - each bit of software may have a different strategy - name, alias, just a filter number, but it's at least consistent for the same device/session/software etc.

`
CREATOR = 'Sequence Generator Pro v3.1.0.454'
-- This seems to have its own mapping
FILTER  = 'Blue    '
FILTER  = 'Green   '
FILTER  = 'Ha      '
FILTER  = 'Red     '

SWCREATE= 'Astro Photography Tool - APT v.3.71'
or SWCREATE= 'Astro Photography Tool - APT v.3.82'
-- Appears to use whatever I have defined myself in the ASCOM driver - user enumerated
FILTER  = 'O3      '
FILTER  = 'S2      '
FILTER  = 'L       '
FILTER  = 'R       '
FILTER  = 'G       '
FILTER  = 'B       '
`

I checked another bit of software, and it seems consistent with the APT one, other than the whitespace has been stripped. From what I can see in my limited dataset of 3 bits of software, at minimum the two keywords of FILTER and IMAGETYP seem to be consistent, even if their enumerations are dynamic depending on the software.

If you need sample data files, please reach out.

Regards,
Turbo

**Comment by robertpascale** [comment]
Confirming the FILTER keyword addition to 4.2.4 Beta 4 works properly, including reading in from pre-existing filelists. This is for FITS files created by Sequence Generator Pro (SGP) from MainSequence software, and also from Astro Photography Tool (APT) software.

**Comment by perdrix52** [comment]
Closed - added to "Where Next"
