### ISSUE TITLE
Idea: Trying to use DSS-live is burning my eyes

### ISSUE THREAD

**Issue by shlomiv** [deepskystacker/DSS#39]
I think DSS-live should have a dark theme.. 

I use it near my scope while taking subs and it scorches my vision at night.

**Comment by perdrix52** [comment]
Good idea, thank you

**Comment by shlomiv** [comment]
Hi there, recently upgraded to the latest version (4.2.1) which is awesome! Any chance to have this issue addressed in the next release?

Love your work, thank you so much!

**Comment by perdrix52** [comment]
So many things to do, so little time.  The old dalog editor code isn't very amenable to "themes" ...

Nonetheless I understand the need very well!

**Comment by perdrix52** [comment]
![DSSLive](https://user-images.githubusercontent.com/20211762/62932208-9fd96480-bdb7-11e9-846b-12aba446fffe.PNG)

Sort of like that?

**Comment by shlomiv** [comment]
Yes, that would be a major improvement!

**Comment by perdrix52** [comment]
OK, we'll do this in the release after 4.2.2.

David

**Comment by SimonCSmith** [comment]
I've created a build of DSS Live with a darker theme and would like some feedback from those here that requested it to see how well it works for them in action. All tabs/sheets have been darkened with the exception of the radio and push buttons on the preferences page. Any popup dialogs (like setting email address and so forth) are not darkened either. For the log page and live last image/stacks though they are fully darkened. You can download the build from the link below - just extract the 7Zip file and replace your existing DSS Live executable. All feedback welcome!

https://drive.google.com/drive/folders/1sKyi_SjoCR2kVcNr02lq7VXBhQ4o7TFw?usp=sharing

**Comment by shlomiv** [comment]
That is fantastic, thank you! 

I will try it out tonight and write my feedback here.

**Comment by shlomiv** [comment]
I ran the version, and it is MUCH better. 

The fonts are a bit dim but not too bad. Perhaps they could be a bit brighter, really not critical.

![image](https://user-images.githubusercontent.com/379063/64406788-90a4aa00-d037-11e9-86b7-577f727a5b86.png)

In the log tab, the new files lines are bright green on gray, which is very hard to read. It actually got killed by the jpeg compression when taking the screenshot since the signal was so low:

![image](https://user-images.githubusercontent.com/379063/64406210-1aec0e80-d036-11e9-8886-b128a5b70fbc.png)

I had to take it again as a png to actually see show it here:

![image](https://user-images.githubusercontent.com/379063/64406426-a2398200-d036-11e9-9983-1061f9a148b4.png)

The graphs were all pretty good:
![image](https://user-images.githubusercontent.com/379063/64406479-c39a6e00-d036-11e9-9516-a54804108e3c.png)

![image](https://user-images.githubusercontent.com/379063/64406490-cbf2a900-d036-11e9-93ca-f00a23b548c6.png)

Only the angle graph, which also uses green for the line, was a bit difficult to see:

![image](https://user-images.githubusercontent.com/379063/64406536-e75db400-d036-11e9-82a2-9c8b9b17b765.png)

There were some artifacts where text would exceed the bounding box. It was reproducible when resizing the window while it was working:

![image](https://user-images.githubusercontent.com/379063/64407305-e3cb2c80-d038-11e9-944d-a64d939f3fd9.png)
 
Overall, this is a big improvement! Especially when this is running while taking subs outside in the dark. Thank you so much for taking the time to do this!

**Comment by SimonCSmith** [comment]
Thanks for the feedback shlomiv - I've addressed the following:
1) Main text font is slightly brighter on the controls
2) Log colours have been tweaked to fit the grey background
3) Graph colours tweaked for clarity

I have not addressed the text overlap part.

A new build (numbered 2) is in the same folder as before - let me know what you think!

**Comment by shlomiv** [comment]
I gave the new build a try, and it looks great! Thank you for doing this. It will be so much more convenient to use this out in the field :)

**Comment by perdrix52** [comment]
Close as will be shipped with 4.2.3
