### ISSUE TITLE
Stacking method not shown in recap file

### ISSUE THREAD

**Issue by farom57** [deepskystacker/DSS#42]
The stacking method is not written in the recap file. It occurred when the average was selected but it was ok for kappa-sigma clipping and auto adaptative average. 

![capture du 2018-10-21 14-18-16](https://user-images.githubusercontent.com/7573799/47266839-32b0c600-d53c-11e8-8f8b-a9fbb1baf39b.png)
[Autosave012.html.txt](https://github.com/LucCoiffier/DSS/files/2499108/Autosave012.html.txt)

**Comment by VPInventions** [comment]
Thanks for the report. This will be fixed in the next release.
