### ISSUE TITLE
Black point and scaling issue

### ISSUE THREAD

**Issue by blemasle** [deepskystacker/DSS#52]
Hi,

I'm facing a strange issue where some of my DNG turn red within DSS. When used as calibration frames, this substract too much data from the final stack.  
As discussed [here](https://www.pentaxforums.com/forums/32-digital-processing-software-printing/380431-black-level-black-point-issue.html), it has to do with black point and dcraw apparently.
Some of the DNG have an `BlackPoint` and `BlackLevel` EXIF tags set and some do not (why ? that's a mystery).
The consequence is that if "Set black point to 0" (`-k 0`) is checked, it overrides those EXIF tags and wrongly scale the image (from my understanding, I'm not familiar with raw usage).

For a good frame to come out of the process, dcraw must use the `BlackPoint` EXIF tag, or the `-k` parameter should be set to that value instead of 0 (which is the same as reading the value from the EXIF).
So, in my case I should always uncheck "Set black point to 0".  Done. :)

But according to the [manpage of dcraw](https://www.cybercom.net/~dcoffin/dcraw/dcraw.1.html), shouldn't the `-D` option be use to load dark frames anyway (as noted in the manpage at the `-K` option description) ?
Shouldn't frames be loaded as is without any scaling ?

Scaled bias frame, black
```text
> dcraw -v -t 0 -4 -T "IMGP9837.DNG"
Loading Pentax K-5 II image from IMGP9837.DNG ...
Scaling with darkness 513, saturation 15867, and
multipliers 2.399911 1.000000 1.352119 1.000000
AHD interpolation...
Converting to sRGB colorspace...
Writing data to IMGP9837.tiff ...
```

Scaled bias frame, red
```text
> dcraw -k 0 -v -t 0 -4 -T "IMGP9837.DNG"
Loading Pentax K-5 II image from IMGP9837.DNG ...
Scaling with darkness 0, saturation 15867, and
multipliers 2.399911 1.000000 1.352119 1.000000
AHD interpolation...
Converting to sRGB colorspace...
Writing data to IMGP9837.tiff ...
``` 

Bias frame, black
```text
> dcraw -D -v -t 0 -4 -T "IMGP9837.DNG"
Loading Pentax K-5 II image from IMGP9837.DNG ...
Building histograms...
Writing data to IMGP9837.tiff ...
```

You'll find [here](https://drive.google.com/file/d/1acys-XaX9ZQoQw_URdfl9DsE7VlMB02k/view) a zip with the relevant test DNG files. Below are an extract of those DNG EXIF tags that seems to be relevant for the problem at hand

```text
======== IMGP9834.DNG
Black Point : 67 67 67 67
Black Level : 67 67 67 67
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1/8000
ISO : 100
======== IMGP9835.DNG
Black Point : 129 129 130 129
Black Level : 129 129 130 129
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1/8000
ISO : 200
======== IMGP9836.DNG
Black Point : 257 257 258 258
Black Level : 257 257 258 258
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1/8000
ISO : 400
======== IMGP9837.DNG
Black Point : 513 513 515 515
Black Level : 513 513 515 515
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1/8000
ISO : 800
======== IMGP9838.DNG
Black Point : 0 0 0 0
Black Level : 0 0 0 0
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1/8000
ISO : 1600
======== IMGP9839.DNG
Black Point : 0 0 0 0
Black Level : 0 0 0 0
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1/8000
ISO : 3200
======== IMGP9922.DNG
Black Point : 511 511 513 512
Black Level : 511 511 513 512
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 2
ISO : 800
======== IMGP9924.DNG
Black Point : 0 0 0 0
Black Level : 0 0 0 0
Picture Mode : Bulb, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1.9
ISO : 800
======== IMGP9926.DNG
Black Point : 0 0 0 0
Black Level : 0 0 0 0
Picture Mode : Manual, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 2
ISO : 1600
======== IMGP9927.DNG
Black Point : 0 0 0 0
Black Level : 0 0 0 0
Picture Mode : Bulb, Off-Auto-Aperture; 1/3 EV steps
Exposure Time : 1.9
ISO : 1600
```

Regards

**Comment by perdrix52** [comment]
The black level for a frame is either in the exif or hard coded in dcraw/libraw for that camera.

We deliberately chose to use -d rather than -D as this applies colour correction (WB) and applies a LINEAR strech from 12/14 bit sto 16 bits.

If you choose the Set black level to 0 option then no black level subtraction is done at all.

You shoudl find that the new version (4.2.0) supports your Pentax K5 so you should be able to process the raw files directly - please let me know if that works for you

**Comment by blemasle** [comment]
Great. I'll try to have a look at it as soon as I can.
Thanks

**Comment by perdrix52** [comment]
You can download the beta from:

https://github.com/LucCoiffier/DSS/releases/tag/4.2.0-Beta-2

 

David

**Comment by perdrix52** [comment]
I did some experiments on my images from a Canon EOS60Da.  The Camera black point is 2047.  If I use Set black point to 0, then they go a horrid shade of red just as you reported.  IMHO you shouldn't use Set Black point to 0 (-k 0) (maybe you would if you're using Bias Frames) but otherwise not.

**Comment by blemasle** [comment]
I am using Bias frames, and they are the problem. As they're not "black" anymore, they substract too much signal from the processed image.

Anyway, that beta seems to had one huge negative effect : it does not matter if I check "Set black point to 0" or not anymore. I always get the red tint no matter what.

You can easily reproduce this by using raw files in [this zip](https://drive.google.com/file/d/1acys-XaX9ZQoQw_URdfl9DsE7VlMB02k/view). Every file shot in Manual mode with ISO =< 800 at 1/8000s (bias frames) present that red tint.

I'm pretty sure the problem lies in the camera itself not being consistent regarding black point/level EXIF management. Those bias frames are the one with black point/level EXIF not set to 0.

At least ton DSS 4.1.1, I can use bias frame by not checking "Set black point to 0". With 4.2.0-beta-2 they're unusable :(

**Comment by perdrix52** [comment]
Are you able to demonstrate the problem with Pentax Raw files rather than DNG files?

**Comment by blemasle** [comment]
The DNG files comes straight from the camera. Pentax supports PEF and DNG files out of the box.
I'll try to set the output to PEF files and see if the issue is still there.

**Comment by blemasle** [comment]
Indeed, the issue does not come up with PEF files. Only with DNG (again, both are coming from the camera). DNG files have both `Black Point` and `Black Level` set whereas PEF only have `Black Point`

```
======== IMGP1595.PEF
Black Point                     : 0 0 0 0
Exposure Time                   : 1/8000
ISO                             : 1600
======== IMGP1596.PEF
Black Point                     : 513 513 516 515
Exposure Time                   : 1/8000
ISO                             : 800
======== IMGP1593.DNG
Black Point                     : 513 513 515 516
Black Level                     : 513 513 515 516
Exposure Time                   : 1/8000
ISO                             : 800
======== IMGP1594.DNG
Black Point                     : 0 0 0 0
Black Level                     : 0 0 0 0
Exposure Time                   : 1/8000
ISO                             : 1600
```

See [pef vs dng zip](https://drive.google.com/file/d/1kYRkKclC9gB5ZE9gy2CXkGsph2bDl0oP/view?usp=sharing)

**Comment by perdrix52** [comment]
Oooh errr!  That's nasty!  Please can you let me know what tool you used to extract the exif data?

**Comment by perdrix52** [comment]
LibRaw reported a black level of 0 for IMGP1593.DNG???  That doesn't seem right.

00000124 2019/06/21 02:27:19.962 011184 000012c4           >Creating 16 bit gray memory bitmap 00007FF4D3B05F50 (D:\Users\amonra\Documents\Astrophotography\DSS Test Images\Pentax black point - pef vs dng\IMGP1593.DNG)
00000125 2019/06/21 02:27:19.967 011184 000012c4           +int __cdecl CRawDecod::LoadRawFile(class CMemoryBitmap *,class CDSSProgress *,int)(RAWUtils.cpp:645)
00000126 2019/06/21 02:27:19.972 011184 000012c4             +int __cdecl CRawDecod::IsRawFile(void)(RAWUtils.cpp:1011)
00000127 2019/06/21 02:27:19.979 011184 000012c4             -int __cdecl CRawDecod::IsRawFile(void)
00000128 2019/06/21 02:27:20.597 011184 000012c4             >Processing Bayer pattern raw image data
00000129 2019/06/21 02:27:20.602 011184 000012c4             >Extracting real image data (excluding the frame) from RawData.raw_image
00000130 2019/06/21 02:27:20.642 011184 000012c4             >Subtracting black level of 0 from raw_image data.

I'll dig deeper!

**Comment by perdrix52** [comment]
What did you use to get that info about the image files - I looked at them using ExifTool but couldn't find an exif tag called "Black Point"  - the "Black Level" tags were there OK for the DNG file.

I think I may need to make the black level code much more complex :(  There's also a cblack array ...

**Comment by perdrix52** [comment]
SVP me dire votre adresse e-mail?

Heidelberg Uni?

**Comment by blemasle** [comment]
Hi. I used the last version of [exiftool](https://www.sno.phy.queensu.ca/~phil/exiftool/)
But I can try with any other you like :)

To extract the above info, I just called `exiftool -BlackPoint -BlackLevel -Iso -ExposureTime IMGP1593.DNG`.

You can reach me at blemasle at gmail dot com (is that kind of trickery still usefull today... I doubt it)

**Comment by perdrix52** [comment]
I tried to send a zip file to you at that email but got: ** The remote server ?? responded with: ** blemasle@gmail.com ??:?? 
[DeepSkyStacker.zip](https://github.com/deepskystacker/DSS/files/3321442/DeepSkyStacker.zip)

Anyway here's the file I tried to email you to try out

**Comment by blemasle** [comment]
Weird. It is the correct address and I indeed did not receive a mail containing a zip from you.
The beta 4 in the zip seems to correct the red tint issue on dng files obtained from the camera ! 👏 

![beta2 vs beta4](https://user-images.githubusercontent.com/5184737/60046754-685c0f00-96c8-11e9-93ed-7502a061bda8.jpg)

**Comment by perdrix52** [comment]
Excellent J

 

Thank you for bringing the problem to our attention and for helping to solve it.

 

Clear skies

David

**Comment by perdrix52** [comment]
Bertrand, If you are happy I will now close this issue
