### ISSUE TITLE
dss does not recognize gain values in fits files

### ISSUE THREAD

**Issue by Hansi123456789** [deepskystacker/DSS#56]
Hi, while dss does recognize different iso settings it does not show different gain values in fits files....
Can you fix this?

**Comment by perdrix52** [comment]
I'm looking at this for release 4.2.2 (currently in development).   Can you give me some pointers where I should look in the fits file for this gain value and what I should do with it (apart from reporting the value)?

**Comment by perdrix52** [comment]
Bump - no reply so far

**Comment by perdrix52** [comment]
This is being done for 4.2.3

**Comment by Hansi123456789** [comment]
Hi sorry, saw your reply only now:

The gain in a ccd is similar to the iso. One should not mix or stack darkfiles with different gain values together. So threat it like the iso parameter or the temperature. Temperature is also listed in fits files. Darks with different gain or temperature should also be separated and only be subtracted from lights with the same temperature or gain....

Where this parameter is? In the fits header. Use a fitsviewer and open a fits file with it. There you can usually see a header with Gain, Temperature and Filter name.

**Comment by perdrix52** [comment]
I didn't know that stuff, but Vitali did - you can try it all when we release 4.2.3 beta 1 - very soon now.

David
