### ISSUE TITLE
Using DSS icon in installer/uninstaller instead of installer default??

### ISSUE THREAD

**Issue by henrysky** [deepskystacker/DSS#64]
I noticed in the latest DSS beta, the default icon of NSIS installer is used instead of DSS. The same happens to the uninstaller icon in Control Panel.

Can you change the icon back to DSS's.

![image](https://user-images.githubusercontent.com/28623434/59553731-3a0f5e80-8f67-11e9-9f27-63d13ea468e4.png)

![image](https://user-images.githubusercontent.com/28623434/59553728-2e239c80-8f67-11e9-9f63-91f092d32a2f.png)

**Comment by perdrix52** [comment]
Oops - thank you - now fixed!

David
