### ISSUE TITLE
Importing/building project guide

### ISSUE THREAD

**Issue by PawelPleskaczynski** [deepskystacker/DSS#67]
Hello, first of all, thank you for open-sourcing this piece of software!
I wanted to learn C/C++ a bit and I thought that at least reading code of application I'm often using would be helpful. I tried to build DSS, so I imported it in Visual Studio Community 2019 via Git, but I'm stuck with this error:
```
Error CMake Error at C:\Users\pawel\Source\Repos\DSS\CFitsIO\CMakeLists.txt:147 (FILE):
  FILE COPY cannot find
  "C:/Users/pawel/source/repos/DSS/CFitsIO/testprog.tpt".	CFITSIO	C:\Users\pawel\Source\Repos\DSS\CFitsIO\CMakeLists.txt	147	
```
at this line:
```
FILE(COPY ${CMAKE_SOURCE_DIR}/testprog.tpt DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
```
Would it be possible to add a build guide to this repository? I think it'd be helpful for beginners like me.
Cheers!

**Comment by perdrix52** [comment]
Huh!  How come you ended up down that rabbit hole?

You open VS2017 (or VS2019 I guess) and open the solution file called DeepSkyStacker.VS2017.sln

You can then build the code

VERY BRAVE to pick on this to learn C/C++  I'd honestly suggest something simpler!

David

**Comment by PawelPleskaczynski** [comment]
Thank you, now I managed to open and build the project properly!

I know it's not a simple project, it's quite complex indeed, but I wanted to see what it's like to work with code like this 😄

**Comment by perdrix52** [comment]
The default development branch is "master" we merge from there into "release" when we are completely happy to do a full (non-beta) release and do the release from the "release" branch.  New development either takes place directly on "master" if simple changes, or on a new branch if more complex.
