### ISSUE TITLE
Turning whitebalancing off during RAW conversion

### ISSUE THREAD

**Issue by IvoJager** [deepskystacker/DSS#83]
Other stacking solutions such as PI and APP have an option (usually set by default) to keep the RAW conversion process from applying any white balancing and camera-dependent matrix multiplication.

The need for this comes forth from the differing signal quality characteristics in the 3 channels. In the case of a Bayer matrix, for example, there are twice as many green samples as there are blue and red samples.

Applications that can take advantage of this fact (e.g. StarTools) for the purpose of maximising signal fidelity are unable to do so when DSS insists on color balancing the dataset (and - worse - applying camera-dependent color correction matrices). Meddling with the color channels creates complex, unpredictable blends of signal vs noise for each color channel.

As the creator of StarTools, this long-standing issue has been the major thing has kept me from recommending DSS as a preferred pre-processing solution companion.

A StarTools user has identified the code that is responsible for this forced whitebalancing;
([original post here](http://forum.startools.org/viewtopic.php?f=10&t=1522#p6527))

> In DSS-4.1.0-Release\DeepSkyStacker\RAWUtils.cpp, line 879, the function
> 
> BOOL CRawDecod::LoadRawFile(CMemoryBitmap * pBitmap, CDSSProgress * pProgress, BOOL bThumb)
> 
> assembles the dcraw command line to import the .CR2 files. It also sets some globals with a call to SetWhiteBalance() at line 996. Those globals aren't use in the dcraw call, though.
> 
> Here are the white balance options LoadRawFile sets for dcraw. The '-r 1 1 1 1' is not to be found in the function.
> bValue = FALSE;
> workspace.GetValue(REGENTRY_BASEKEY_RAWSETTINGS, _T("AutoWB"), bValue);
> if (bValue)
> {
> // Automatic WB
> argv[argc] = _T("-a");
> argc++;
> };
> 
> bValue = FALSE;
> workspace.GetValue(REGENTRY_BASEKEY_RAWSETTINGS, _T("CameraWB"), bValue);
> if (bValue)
> {
> // Camera WB (is possible)
> argv[argc] = _T("-w");
> argc++;
> };
> 
> if (!m_bColorRAW)
> {
> // Document mode
> argv[argc] = _T("-d");
> argc++;
> };
> 

To be clear, the proposed **-r 1 1 1 1** option sets a custom white balance of 1.0 for the RGGB samples. 
From the dcraw help;

> -r <r g b g> Set custom white balance

Please do let me know if anything is not clear. Clear skies!

**Comment by perdrix52** [comment]
Hi Ivo, the current code doesn't use DcRaw at all, and we do our own WB processing.  However I while I am prepared to consider allowing an option to bypass white balance processing, I don't understand why it's a problem.  The code we use is very simple:

			//
			// The image data needs to be scaled to the "white balance co-efficients"
			// Currently do not handle "Auto White Balance"
			//
			float pre_mul[4];

			if (1 == O.use_camera_wb && -1 != C.cam_mul[0])
			{
				ZTRACE_RUNTIME("Using Camera White Balance (as shot).");
				memcpy(pre_mul, C.cam_mul, sizeof pre_mul);
			}
			else
			{
				ZTRACE_RUNTIME("Using Daylight White Balance.");
				memcpy(pre_mul, C.pre_mul, sizeof pre_mul);
			}
			ZTRACE_RUNTIME("White balance co-efficients being used are %f, %f, %f, %f",
				pre_mul[0], pre_mul[1], pre_mul[2], pre_mul[3]);

			if (0 == pre_mul[3]) pre_mul[3] = P1.colors < 4 ? pre_mul[1] : 1;

			//
			// Now apply a linear stretch to the raw data, scale to the "saturation" level
			// not to the value of the pixel with the greatest value (which may be higher
			// than the saturation level).
			//

			double dmin, dmax; int c = 0;

			for (dmin = DBL_MAX, dmax = c = 0; c < 4; c++)
			{
				if (dmin > pre_mul[c])
					dmin = pre_mul[c];
				if (dmax < pre_mul[c])
					dmax = pre_mul[c];
			}

			float scale_mul[4];

			for (c = 0; c < 4; c++)	scale_mul[c] = (pre_mul[c] /= dmin) * (65535.0 / C.maximum);

			ZTRACE_RUNTIME("Maximum value pixel has value %d", C.data_maximum);
			ZTRACE_RUNTIME("Saturation level is %d", C.maximum);
			ZTRACE_RUNTIME("Applying linear stretch to raw data.  Scale values %f, %f, %f, %f",
				scale_mul[0], scale_mul[1], scale_mul[2], scale_mul[3]);

#if defined(_OPENMP)
#pragma omp parallel for default(none)
#endif
			for (int row = 0; row < S.height; row++)
			{
				for (int col = 0; col < S.width; col++)
				{
					// What colour will this pixel become
					int colour = rawProcessor.COLOR(row, col);

					register float val = scale_mul[colour] *
						(float)(RAW(row, col));
					RAW(row, col) = max(0, min(int(val), 65535));
				}
			}

So what could that be doing that messes up your code?
David

**Comment by IvoJager** [comment]
Thanks for the lighting quick response David - it is much appreciated!
Looking at the code, pre_mul[0], pre_mul[1], pre_mul[2], pre_mul[3] should all be forced to 1.0 for white balancing to not take place. Currently, it appears these are set by a copy from either C.cam_mul or C.pre_mul. I'm not quite sure where these, in turn, are set.

To recap, the problem occurs when the values in pre_mul are anything but 1.0 (as would be accomplished by the -r 1 1 1 1 parameter).
This causes the signal to be multiplied by an amount that cannot be known by the program used to post-process the stack. Because these multipliers cannot be known, it cannot be known by the program post-processing the stack how the signal and its noise component were impacted in each channel. This in turn makes the correct weights for creating a synthetic luminance dataset unknown. This in turn yields to a noisier synthetic luminance frame than needed, leading in turn to a poorer image and less effective results from algorithms such as deconvolution.

In addition, when stacking an image shot with the increasingly popular duoband filters for DSLRs, white balancing becomes rather meaningless, and the impact on synthetic luminance creation even more detrimental.

Does this make sense?

**Comment by perdrix52** [comment]
I definitely could make this change and it would be moderately simple to do (though it has impact way beyond the code I pointed you to).   It would be part of the next release if done.  Would I be correct to think that you still want the code to scale 12 and 14 bit data to 16 bit?

Darn - this would mean even MORE translation work to be done.

David

**Comment by IvoJager** [comment]
Sorry about the translation work, but you would make a lot of people very, very happy indeed! :)
Please keep the proper global scaling in place, as-is. It's just the disparity in color channel scaling (aka white balancing) we're trying to eliminate for people with our use cases. Say the word and I'll bring the good news to the StarTools forums!

**Comment by perdrix52** [comment]
This will be added to to the next release (4.2.3).

David

**Comment by IvoJager** [comment]
That's fantastic news David - thank you very much!
