### ISSUE TITLE
Feature request - maintain image zoom and position when file changes

### ISSUE THREAD

**Issue by red-man** [deepskystacker/DSS#93]
I like to manually review all of my light images prior to including them in the stack.  I will zoom in on a portion of the image and verify the stars are to my liking.  When I select a different image it resets the zoom.  It would be helpful if there was an option to keep the zoom and view port of the image when I change to a new image if the image is the same dimensions.  Are you open to adding a feature like that?

**Comment by perdrix52** [comment]
Hi there, Open to suggestion yes - but I can't see how this could be done with the current code :(!

I'll see if anyone else on the team has any ideas. ...

**Comment by perdrix52** [comment]
A thought: Are you aware of what the "four squares" icon in the top right of the window does?

That's this one: 
![image](https://user-images.githubusercontent.com/20211762/75145299-975fd000-56f0-11ea-8103-604b9bb0d033.png)

Zooms in all four corners simultaneously - may well do what you need.

**Comment by red-man** [comment]
Yes that is almost what I need it just doesn't seem to have much zoom by default and if I do zoom in then it resets the zoom when changing images.

**Comment by perdrix52** [comment]
This will be resolved in Version 5
