### ISSUE TITLE
Version for Linux

### ISSUE THREAD

**Issue by e-reznik** [deepskystacker/DSS#94]
Hello,

is it possible to compile and run it on a Linux machine?
I (and many more Linux users) would be glad about a tutorial.

Kind regards

**Comment by karolbe** [comment]
Use Wine. DSS works just fine under Wine on Linux. I think it is even faster than on Windows.

**Comment by perdrix52** [comment]
To e-resnik - No if you look at the code, it is very Windows ...

To karolbe many have failed to setup Wine so that DSS will work.  None of the developers are Wine savvy.  Are you able to email a tutorial to me [mailto:david.partridge@perdrix.co.uk] on how to set it up so DSS will work and I will post it on the Wiki.  Please assume limited Linux skills.

**Comment by NK308** [comment]
Does this still hold, after the ui now seems to be migrated to Qt?

**Comment by perdrix52** [comment]
That's very much work in progress and is taking a lot longer than I expected.

Any Qt programmers out there?

**Comment by openastroproject** [comment]
> Any Qt programmers out there?

I've been idly pondering on the idea of a Qt version of DSS (specifically with a view to having a Linux/MacOS native release) for some time, though not sufficiently that I've bothered to do anything about it.  I could be tempted to put a bit of time into it though.  The main barrier for me is that I know very little, probably even less, about Windows.

**Comment by perdrix52** [comment]
You'd need to speak Windows/MFC as well to be able to help

**Comment by ErwanDL** [comment]
Hello, I was just wondering what the main obstacles for envisioning a Linux version were at the moment? Is it mostly UI code that is Windows-specific, or is the actual processing logic relying on Windows/DX APIs or Windows-only syscalls? Is the current code deeply coupled with these Windows-only components, or could a compatibility layer with Linux APIs be relatively ""easily"" (note the big quotes!) swapped in?

I can absolutely not guarantee that I would have either the time or the skills to work on this, but I was just thinking that having a clearer picture of what the task really represents could create some emulation among folks :slightly_smiling_face:

**Comment by mtoeltsch** [comment]
GUI: David is working on replacing Windows/MFC by Qt. This is still ongoing.
Windows threads: I replaced them by Openmp in #132.
Windows file system/path names: Not sure about this, but I expect issues with it (path names with backslash, file attributes, ...).
Date/Time: It's still using Windows specific stuff (GetTickCount, ...).
Windows messaging: Still used, needs replacement. Partly quite strongly coupled, e.g. in CProcessingDlg (using SetTimer, ...).
Windows GDI+: Still used, partly strongly coupled. Needs to be replaced with something platform independent.
Windows classes: Things declared in windef.h are still used (e.g. points, rects, ...).
Windows Clipboard: Not sure about this (will David replace it by Qt too?), but at the moment it's using Windows calls.
Stack tracing/crash handling: Uses Windows specific stuff.
Windows exception handling: Not sure, but I think this is also used.
Other Windows specific stuff: LPCSTR, CString, __declspec, ...

As you can see, hundreds of smaller or larger things to do. This is really a HUGE task.
Some Windows specific things are strongly coupled (unfortunately!).

**Comment by ErwanDL** [comment]
Thanks for the writeup @mtoeltsch! I have spent a few hours last week-end figuring out what parts exactly still use MFC and are yet to be replaced with Qt, I'll create an issue this week-end to sum up my findings, and see if you guys can point me to easy tasks and bits to start with. But I read @perdrix52 had a lot of local work waiting to be pushed, so maybe it will invalidate the mental snapshot that I had.

Among the different bullet points that you listed, do you have a suggestion for a good first one to tackle? I started to get familiar with parts of the codebase these past days, but I reckon not all tasks are equal in complexity :)

**Comment by mtoeltsch** [comment]
Hi Erwan,
you could start with getting rid of Windef.h. 
Note what is defined in Common.h hidden behind #if !defined(_WINDOWS_).

**Comment by perdrix52** [comment]
Erwan, please can you let me have your email address so I can invite you to join the Slack discussion group

**Comment by perdrix52** [comment]
In progress - closed
