### ISSUE TITLE
Checking some files makes comet tab disappear

### ISSUE THREAD

**Issue by shlomiv** [deepskystacker/DSS#95]
I attempted to integrate some comet data I gathered last night.

Using 4.2.3 (and 4.1.1), when checking all files, manually marking comet (using shift) in first and last does not enable the comet tab. After laborious testing (over 100 files in just one tested channel), it seems that some files - consistently - make the tab not appear. There is nothing different about these files. I will upload screenshots and if you would like I could upload one offending file and one working file for you to examine.

**Comment by shlomiv** [comment]
![NoComet](https://user-images.githubusercontent.com/379063/78066394-bda90900-7349-11ea-807f-b3e938fc5fa0.PNG)
![YesComet](https://user-images.githubusercontent.com/379063/78066397-beda3600-7349-11ea-9cbf-a44c5837a52e.PNG)

**Comment by shlomiv** [comment]
The strange thing - when I try to integrate only these two files (The yellow and the one above), it does show the comet tab.. :|

**Comment by shlomiv** [comment]
Ok... I think I am making some progress.. It seems that some frames require a manual setting of the comet. It makes the process pretty tedious, as the program does not say which files needs manual comet positioning.

The way I am going about it is:
1. Manually select comet in first and last
2. Check the next batch of frames (say 10 frames)
3. Check if the comet tab appears
4. If it does, move to the goto 2
5. If it does not, manually select the comet in the last image of the batch that does not have comet selected, goto 3
6. When done, stack all frames..

**Comment by perdrix52** [comment]
Please use the DeepSkyStacker mailing list at groups.io for support.  There have been comet stacking tutorials posted there.

**Comment by shlomiv** [comment]
Thanks @perdrix52
