### ISSUE TITLE
Add support to .cr3

### ISSUE THREAD

**Issue by Ilvedia** [deepskystacker/DSS#96]
The LibRaw-0.19.5 allows the integration of the . rw3 formats of the latest cameras.

Thanks

**Comment by perdrix52** [comment]
The 201910 development snapshot (AKA Beta) allows that - this has been discussed at length on the mailing list.   we will support CR3 when LibRaw release a stable release that does.

Please ask for support at groups.io/g/DeepSkyStacker not here - we use this for validated bugs we don't fix immediately and developers use for planning.

**Comment by karolbe** [comment]
@Ilvedia see https://github.com/karolbe/DSS/tree/libraw-master - I built DSS with the latest libraw snapshot, CR3 files are supported in that (obviously unofficial) build.

**Comment by perdrix52** [comment]
I was pretty certain it would work ...  Delighted it works for you.

**Comment by Ilvedia** [comment]
Thank you so much for all your work
