### ISSUE TITLE
Image size is off.

### ISSUE THREAD

**Issue by karolbe** [deepskystacker/DSS#97]
I noticed that when I take images in CR3 format and then convert to DNG via Adobe DNG converter then the image size reported in DSS is incorrect. Images are reported to have 6732x4488 pixels while in reality they are 6720x4480 pixels (I confirmed with e.g Photoshop / Adobe Bridge).

The issue is now that I am unable to process images when I have darks/flats/lights in different formats as DSS does not allow for different image sizes.

![image](https://user-images.githubusercontent.com/1939578/78470593-194d0b00-772b-11ea-950c-797f62cbbfb8.png)

**Comment by perdrix52** [comment]
1) This issues page is primarily used by the developers to log improvement requests or bugs after they've been validated.

2) For DSS support please use the mailing list on groups.io: <https://groups.io/g/DeepSkyStacker/>

3) If DNG conversion messes up the image size I can't help you.  If you're using CR3 I understand why you convert to DNG as libraw support for CR3 isn't there yet.  But surely all the images from a given camera will end up the same size after conversion.
